### ISSUE TITLE
wrap = {false} on <View> with long text causes memory issues , causes display issues on <Text> 

### ISSUE THREAD

**Issue by jenisewalters** [diegomura/react-pdf#1018]
**Describe the bug**
When I put wrap = {false} on a <View> with long text my application fails with a memory issue when I put wrap = {false} on a <Text > component with long text the display is jumbled

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to https://react-pdf.org/repl
2. Copy and paste this into the playground 

const Quixote = () => (
  <Document>
    <Page style={styles.body}>
      <Text style={styles.header} fixed>
        ~ Created with react-pdf ~
      </Text>
      <Text style={styles.title}>Don Quijote de la Mancha</Text>
      <Text style={styles.author}>Miguel de Cervantes</Text>
      <Image
        style={styles.image}
        src="/images/quijote1.jpg"
      />
      <View wrap={false}>
      <Text style={styles.subtitle}>
        Capítulo I: Que trata de la condición y ejercicio del famoso hidalgo D.
        Quijote de la Mancha
      </Text>
      <Text style={styles.text}>
        En un lugr de la Mancha, de cuyo nombre no quiero acordarme, no ha
        mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga
        antigua, rocín flaco y galgo corredor. Una olla de algo más vaca que
        carnero, salpicón las más noches, duelos y quebrantos los sábados,
        lentejas los viernes, algún palomino de añadidura los domingos,
        consumían las tres partes de su hacienda. El resto della concluían sayo
        de velarte, calzas de velludo para las fiestas con sus pantuflos de lo
        mismo, los días de entre semana se honraba con su vellori de lo más
        fino. Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina
        que no llegaba a los veinte, y un mozo de campo y plaza, que así
        ensillaba el rocín como tomaba la podadera. Frisaba la edad de nuestro
        hidalgo con los cincuenta años, era de complexión recia, seco de carnes,
        enjuto de rostro; gran madrugador y amigo de la caza. Quieren decir que
        tenía el sobrenombre de Quijada o Quesada (que en esto hay alguna
        diferencia en los autores que deste caso escriben), aunque por
        conjeturas verosímiles se deja entender que se llama Quijana; pero esto
        import	a poco a nuestro cuento; basta que en la narración dél no se salga
        un punto de la verdad
        
        En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha
        mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga
        antigua, rocín flaco y galgo corredor. Una olla de algo más vaca que
        carnero, salpicón las más noches, duelos y quebrantos los sábados,
        lentejas los viernes, algún palomino de añadidura los domingos,
        consumían las tres partes de su hacienda. El resto della concluían sayo
        de velarte, calzas de velludo para las fiestas con sus pantuflos de lo
        mismo, los días de entre semana se honraba con su vellori de lo más
        fino. Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina
        que no llegaba a los veinte, y un mozo de campo y plaza, que así
        ensillaba el rocín como tomaba la podadera. Frisaba la edad de nuestro
        hidalgo con los cincuenta años, era de complexión recia, seco de carnes,
        enjuto de rostro; gran madrugador y amigo de la caza. Quieren decir que
        tenía el sobrenombre de Quijada o Quesada (que en esto hay alguna
        diferencia en los autores que deste caso escriben), aunque por
        conjeturas verosímiles se deja entender que se llama Quijana; pero esto
        import	a poco a nuestro cuento; basta que en la narración dél no se salga
        un punto de la verdad
        En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha
        mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga
        antigua, rocín flaco y galgo corredor. Una olla de algo más vaca que
        carnero, salpicón las más noches, duelos y quebrantos los sábados,
        lentejas los viernes, algún palomino de añadidura los domingos,
        consumían las tres partes de su hacienda. El resto della concluían sayo
        de velarte, calzas de velludo para las fiestas con sus pantuflos de lo
        mismo, los días de entre semana se honraba con su vellori de lo más
        fino. Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina
        que no llegaba a los veinte, y un mozo de campo y plaza, que así
        ensillaba el rocín como tomaba la podadera. Frisaba la edad de nuestro
        hidalgo con los cincuenta años, era de complexión recia, seco de carnes,
        enjuto de rostro; gran madrugador y amigo de la caza. Quieren decir que
        tenía el sobrenombre de Quijada o Quesada (que en esto hay alguna
        diferencia en los autores que deste caso escriben), aunque por
        conjeturas verosímiles se deja entender que se llama Quijana; pero esto
        import	a poco a nuestro cuento; basta que en la narración dél no se salga
        un punto de la verdad
      </Text>
      </View>
    
      <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => (
        `${pageNumber} / ${totalPages}`
      )} fixed />
    </Page>
  </Document>
);

Font.register({
  family: 'Oswald',
  src: 'https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf'
});

const styles = StyleSheet.create({
  body: {
    paddingTop: 35,
    paddingBottom: 65,
    paddingHorizontal: 35,
  },
  title: {
    fontSize: 24,
    textAlign: 'center',
    fontFamily: 'Oswald'
  },
  author: {
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 40,
  },
  subtitle: {
    fontSize: 18,
    margin: 12,
    fontFamily: 'Oswald'
  },
  text: {
    margin: 12,
    fontSize: 14,
    textAlign: 'justify',
    fontFamily: 'Times-Roman'
  },
  image: {
    marginVertical: 15,
    marginHorizontal: 100,
  },
  header: {
    fontSize: 12,
    marginBottom: 20,
    textAlign: 'center',
    color: 'grey',
  },
  pageNumber: {
    position: 'absolute',
    fontSize: 12,
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: 'center',
    color: 'grey',
  },
});

ReactPDF.render(<Quixote />);

3. You will see that the title and text is jumbled and does not properly display
4. If you change the <Text> component to a <View> with wrap = false the pdf will not load and the following error is seen in the console. 

repl:1 Uncaught (in promise) abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 134217728, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (https://react-pdf.org/_next/static/chunks/f057a831.1e1fea788e7ff50480fe.js:1:15135)
    at stackTrace (https://react-pdf.org/_next/static/chunks/f057a831.1e1fea788e7ff50480fe.js:1:15295)
    at abort (https://react-pdf.org/_next/static/chunks/f057a831.1e1fea788e7ff50480fe.js:1:359308)
    at abortOnCannotGrowMemory (https://react-pdf.org/_next/static/chunks/f057a831.1e1fea788e7ff50480fe.js:1:15824)
    at enlargeMemory (https://react-pdf.org/_next/static/chunks/f057a831.1e1fea788e7ff50480fe.js:1:16283)
    at fC (https://react-pdf.org/_next/static/chunks/f057a831.1e1fea788e7ff50480fe.js:1:348772)
    at jS (https://react-pdf.org/_next/static/chunks/f057a831.1e1fea788e7ff50480fe.js:1:315246)
    at Te (https://react-pdf.org/_next/static/chunks/f057a831.1e1fea788e7ff50480fe.js:1:104322)
    at Ki (https://react-pdf.org/_next/static/chunks/f057a831.1e1fea788e7ff50480fe.js:1:150179)
    at Xi (https://react-pdf.org/_next/static/chunks/f057a831.1e1fea788e7ff50480fe.js:1:150271)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

If this is not the correct usage please advise. If the text is too long I would like a better error message and for react-pdf not to hang on the memory issue

**Comment by jenisewalters** [comment]
This is a duplicate of 
https://github.com/diegomura/react-pdf/issues/874
