### ISSUE TITLE
Receiving this error "ERROR RangeError [ERR_OUT_OF_RANGE]" on creating PDF

### ISSUE THREAD

**Issue by kartikluke** [diegomura/react-pdf#1055]
**Describe the bug**
Getting this error `ERROR RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be an integer. Received NaN at boundsError` when trying to print some PDFs. It seems to reliably happen depending on input and I'm trying to debug what is causing it exactly but it would be helpful if someone has context on what the error means.

**Error stacktrace**
```
ERROR RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be an integer. Received NaN at boundsError (internal/buffer.js:43:11) 
at Buffer.readInt16BE (internal/buffer.js:461:5) 
at DecodeStream.(anonymous function) [as readInt16BE] (/var/task/handler.js:76777:35) 
at NumberT.decode (/var/task/handler.js:38509:38) 
at Struct._parseFields (/var/task/handler.js:81331:22) 
at Struct.decode (/var/task/handler.js:81296:12) 
at TTFGlyph._getCBox (/var/task/handler.js:194937:28) 
at TTFGlyph._getMetrics (/var/task/handler.js:195195:21) 
at TTFGlyph.get$$1 (/var/task/handler.js:194832:19) 
at TTFGlyph.descriptor.get (/var/task/handler.js:183618:23)
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Running on AWS Lambda
 - React-pdf version [e.g. v1.1.0] 1.6.2

**Comment by kartikluke** [comment]
Appears to be that this error is thrown when printing glyphs that aren't available in the font in this case there were Hindi glyphs in the invoice.
