### ISSUE TITLE
Can't get examples to run

### ISSUE THREAD

**Issue by buesing** [diegomura/react-pdf#106]
Hi, I'm having trouble getting the examples to run. I cloned the repo with 
`git clone https://github.com/diegomura/react-pdf.git`, then
`cd react-pdf`
`yarn install`
```
 ~/dev/react-pdf ±master⚡ > yarn example -- fractals
yarn example v0.15.1
$ "babel-node ./examples/index.js" fractals
sh: babel-node ./examples/index.js: No such file or directory
error Command failed with exit code 127.
info Visit http://yarnpkg.com/en/docs/cli/example for documentation about this command.
```
Although the file `./examples/index.js` is actually there. Then I tried running babel-node directly:
```
babel-node ./examples/index.js fractals
{ Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/moriz/dev/react-pdf/examples/fractals/index.js:3:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/moriz/.nvm/versions/node/v7.5.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/moriz/.nvm/versions/node/v7.5.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12) code: 'MODULE_NOT_FOUND' }
```
I tried installing the react package in the root dir with yarn add react, then I'm getting this error, after which I'm not sure anymore what to do:
```
 ~/dev/react-pdf ±master⚡ > babel-node ./examples/index.js fractals
{ Error: Cannot find module '@react-pdf/core'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/moriz/dev/react-pdf/packages/react-pdf-node/lib/index.js:15:13)
    at Module._compile (module.js:571:32)
    at loader (/Users/moriz/.nvm/versions/node/v7.5.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/moriz/.nvm/versions/node/v7.5.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12) code: 'MODULE_NOT_FOUND' }
```

Node version v7.5.0
yarn version 0.15.1
macOS Sierra 10.12.4

**Comment by diegomura** [comment]
Hi @buesing.
Does `yarn install` run `lerna bootrstap` when you executed? This might be the cause of the missing modules errors.

**Comment by buesing** [comment]
It does. Here's the complete output of `yarn install`:

```
yarn install v0.15.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
$ npm run build

> @react-pdf/build@0.1.0 build /Users/moriz/dev/react-pdf
> lerna run build --ignore @react-pdf/example-*

lerna info version 2.0.0-rc.5
lerna info ignore @react-pdf/example-*

> @react-pdf/core@0.2.2 build /Users/moriz/dev/react-pdf/packages/react-pdf
> babel ./src --out-dir ./lib

src/Stylesheet/index.js -> lib/Stylesheet/index.js
src/Stylesheet/transformStyles.js -> lib/Stylesheet/transformStyles.js
src/Stylesheet/yogaValue.js -> lib/Stylesheet/yogaValue.js
src/elements/Base.js -> lib/elements/Base.js
src/elements/Document.js -> lib/elements/Document.js
src/elements/Image.js -> lib/elements/Image.js
src/elements/Link.js -> lib/elements/Link.js
src/elements/Page.js -> lib/elements/Page.js
src/elements/Text.js -> lib/elements/Text.js
src/elements/View.js -> lib/elements/View.js
src/elements/index.js -> lib/elements/index.js
src/index.js -> lib/index.js
src/renderer.js -> lib/renderer.js
src/utils/image.js -> lib/utils/image.js
src/utils/jpeg.js -> lib/utils/jpeg.js
src/utils/pageSizes.js -> lib/utils/pageSizes.js

> @react-pdf/node@0.2.2 build /Users/moriz/dev/react-pdf/packages/react-pdf-node
> babel ./src --out-dir ./lib

src/index.js -> lib/index.js

> @react-pdf/dom@0.2.2 build /Users/moriz/dev/react-pdf/packages/react-pdf-dom
> babel ./src --out-dir ./lib

src/Document.js -> lib/Document.js
src/index.js -> lib/index.js
lerna success run Ran npm script 'build' in packages:
lerna success - @react-pdf/dom
lerna success - @react-pdf/node
lerna success - @react-pdf/core
✨  Done in 10.00s.
```

**Comment by diegomura** [comment]
Can you try doing a manual `lerna bootstrap`?

**Comment by diegomura** [comment]
@buesing glad to hear that! Thanks!!
