### ISSUE TITLE
Too much text in a "Text" makes react-pdf crash

### ISSUE THREAD

**Issue by LTMXcitrus** [diegomura/react-pdf#1085]
**Describe the bug**
When I use a Text component with lots of text in it and with linebreaks, the application crashed.
It does not appear to be linked with the amount of characters:
- (Scenario A) I tried with around 7 000 chars and line breaks -> the application crashed
- (Scenario B) I tried with one word of 10 000 characters, the text obviously overflows (I disabled hyphenation) but the application does not crash.

So I tried the Scenario C: copy pasted scenario A but in several Text (manually inserted linebreaks, it does not crash, no matter how many Text component I put in there, as long as each Text component is not too long.

By "the application crashed" I mean that I always get the same following error:

____________________________________________________________________________________________________
abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 134217728, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error: 
    at jsStackTrace (/home/matthieu/workspace/appli-by-fa/back/pdf-service/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:443:15)
    at stackTrace (/home/matthieu/workspace/appli-by-fa/back/pdf-service/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:453:14)
    at abort (/home/matthieu/workspace/appli-by-fa/back/pdf-service/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:9808:182)
    at abortOnCannotGrowMemory (/home/matthieu/workspace/appli-by-fa/back/pdf-service/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:457:5)
    at enlargeMemory (/home/matthieu/workspace/appli-by-fa/back/pdf-service/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:459:5)
    at FC (/home/matthieu/workspace/appli-by-fa/back/pdf-service/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:9628:49)
    at oB (/home/matthieu/workspace/appli-by-fa/back/pdf-service/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:8461:17)
    at qC (/home/matthieu/workspace/appli-by-fa/back/pdf-service/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:9500:13)
    at sf (/home/matthieu/workspace/appli-by-fa/back/pdf-service/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:3287:31)
    at Kq (/home/matthieu/workspace/appli-by-fa/back/pdf-service/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:5995:87)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
____________________________________________________________________________________________________

During my investigations, I found this property: "hyphenationCallback" for Text Component, which appears to be an integer with a default value of 600. It does not seem to be used in the source code, on the other hand I found a "hyphenationPenalty" in the code, which is an expected props for Text but is not documented. Possible typo/mistake ? Perhaps it does not have anything to do with my problem.

Many thanks to @diegomura for the amazing work here :)

**Comment by rkhayat** [comment]
- **Occurs** if you open `https://react-pdf.org/repl` and edit a `<Text/>` component to have a lot of text. (seems to use 1.6.12 currently)

- **Does not Occur** in version `1.5.2`

**Comment by ksmithut** [comment]
Doing some local tests, I can confirm it correctly renders in `1.5.2`, but in `1.5.3` it breaks with the `Cannot enlarge memory arrays` error.

**Comment by ksmithut** [comment]
I was able to chunk the text to pretty large amounts, though maybe available resources on the computer makes a difference. Here are snippets of the code I used:

```js
function MyComponent ({ value }) {
  return chunkText(value, 3000).map((chunk, index) => {
    return <Text key={index}>{chunk}</Text>
  })
}

const NEWLINE = new Set(['\n'])
const PUNCTUATION = new Set(['.', '?', '!'])
const DIVISION = new Set([',', ';'])
const SPACE = new Set([' '])

/**
 * @param {string} value
 * @param {number} maxLength
 */
function chunkText (value, maxLength) {
  const chunks = []
  while (value?.length) {
    const chunk = value.substr(0, maxLength)
    const splitIndex =
      findLast(chunk, NEWLINE) ??
      findLast(chunk, PUNCTUATION) ??
      findLast(chunk, DIVISION) ??
      findLast(chunk, SPACE) ??
      chunk.length - 1
    chunks.push(value.substr(0, splitIndex + 1))
    value = value.substr(splitIndex + 1)
  }
  return chunks
}

/**
 * @param {string} string
 * @param {Set<string>} chars
 */
function findLast (string, chars) {
  for (let i = string.length - 1; i >= 0; i--) {
    if (chars.has(string[i])) return i
  }
  return null
}
```
