### ISSUE TITLE
ReferenceError: Cannot access 'GPOSLookup' before initialization

### ISSUE THREAD

**Issue by oswaldoacauan** [diegomura/react-pdf#1287]
```js
ReferenceError: Cannot access 'GPOSLookup' before initialization
    at Object.<anonymous> (/Users/oswaldoacauan/Projects/movinga/truck/trolley/node_modules/@react-pdf/fontkit/lib/fontkit.cjs.js:2727:80)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.require (/Users/oswaldoacauan/Projects/movinga/truck/trolley/node_modules/require-in-the-middle/index.js:43:24)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/oswaldoacauan/Projects/movinga/truck/trolley/node_modules/@react-pdf/font/lib/index.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.require (/Users/oswaldoacauan/Projects/movinga/truck/trolley/node_modules/require-in-the-middle/index.js:43:24)
    at require (internal/modules/cjs/helpers.js:88:18)```

**Comment by oswaldoacauan** [comment]
This happens when rendering PDF's on the server-side. Not sure if its happening in the client.
