### ISSUE TITLE
DOC: How do I run an example?

### ISSUE THREAD

**Issue by MartinThoma** [diegomura/react-pdf#136]
I think a bit more documentation regarding the installation / how to run an example would be good.

I just tried:

```
$ yarn example -- examples/fractals               
yarn example v0.27.5
$ babel-node ./examples/index.js "examples/fractals"
Running the examples/fractals example
{ Error: Cannot find module './examples/fractals/index'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at runExample (/home/math/Github/react-pdf/examples/index.js:21:5)
    at Object.<anonymous> (/home/math/Github/react-pdf/examples/index.js:38:3)
    at Module._compile (module.js:570:32)
    at loader (/home/math/Github/react-pdf/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/math/Github/react-pdf/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
Done in 1.26s.

```

I would like to see a section

```
## Installation
react-pdf is installed via [yarn](https://github.com/yarnpkg/yarn):

$ git clone https://github.com/diegomura/react-pdf.git
$ cd react-pdf
$ yarn install
```

**Comment by diegomura** [comment]
Thanks for the suggestion. I'll add something like that.
Regarding your snippet, you should run `yarn example -- fractals` only, without the `examples/` prefix

**Comment by MartinThoma** [comment]
You're welcome :-)

Did you know that you can add `closes #136` to a commit message and Github closes that issue as soon as the commit is in master? It then also links the commit within the issue. I think issues should stay open until they are fixed / rejected.

**Comment by diegomura** [comment]
I knew that, yes. 
I do it with the big issues. In this case I just updated the README, so I assume there was no need 😉 
I will take that into account for future times

**Comment by biagiola** [comment]
I have a problem with run the examples. When I run: yarn example -- fractals and it shows me this error:
error Command "examples/" not found. Did you mean "examples"?

After that I try: yarn examples -- fractals and show this error now:
ERR! lerna Unknown argument: fractals
error Command failed with exit code 1.

Those errors are the same in windows 11 and ubuntuo 20.04 lts. I don't if I have to run some steps before to run the examples.
