### ISSUE TITLE
Breaks while Build

### ISSUE THREAD

**Issue by VrajSolanki** [diegomura/react-pdf#162]
machine: Linux
node version: 8, Error: invalid ELF header
8-alpine, 7-alpine: Exec format error

command: babel-node ./dist/index.js

```
module.js:664
 return process.dlopen(module, path._makeLong(filename));

Error: Error loading shared library /src/node_modules/@react-pdf/core/bin/8/nbind.node: Exec format error
at Object.Module._extensions..node (module.js:664:18)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)
at Function.Module._load (module.js:489:3)
at Module.require (module.js:579:17)
at require (internal/module.js:11:18)
at initNode (/src/node_modules/nbind/dist/nbind.js:141:15)
at /src/node_modules/nbind/dist/nbind.js:115:13
at findCompiledModule (/src/node_modules/nbind/dist/nbind.js:79:13)
at find (/src/node_modules/nbind/dist/nbind.js:93:13)
ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pdf-generator@0.2.0 dist: `babel-node ./dist/index.js`
npm ERR! Exit status 1
ERR!
ERR! Failed at the pdf-generator@0.2.0 dist script.
ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by diegomura** [comment]
In which OS are you running this?

**Comment by VrajSolanki** [comment]
rancher os

**Comment by diegomura** [comment]
There are some issues when running on Linux (#144).
I've been working on solving these, but without success yet. Try manually precompiling (as it says in that ticket)
