### ISSUE TITLE
NextJS support

### ISSUE THREAD

**Issue by bdelamotte** [diegomura/react-pdf#1817]
**Describe the bug**
I am trying the example out but I get the following error:
```
ReferenceError: document is not defined
    at eval (webpack-internal:///./pages/dashboard/admin/evictionReport.jsx:94:16)
    at Object../pages/dashboard/admin/evictionReport.jsx (/Users/bdelamotte/repos/partnyr/partnyr-next-app/.next/server/pages/dashboard/admin/evictionReport.js:22:1)
    at __webpack_require__ (/Users/bdelamotte/repos/partnyr/partnyr-next-app/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/bdelamotte/repos/partnyr/partnyr-next-app/.next/server/pages/dashboard/admin/evictionReport.js:76:52)
    at /Users/bdelamotte/repos/partnyr/partnyr-next-app/.next/server/pages/dashboard/admin/evictionReport.js:77:28
    at Object.<anonymous> (/Users/bdelamotte/repos/partnyr/partnyr-next-app/.next/server/pages/dashboard/admin/evictionReport.js:80:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
```

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Create new nextjs application.
2. Create a new page under pages/test.tsx
3. paste in the following code
```
import React from 'react';
import ReactDOM from 'react-dom';
import pdf from '@react-pdf/renderer'


const { Document, Page, Text, View, StyleSheet, PDFViewer } = pdf;

// Create styles
const styles = StyleSheet.create({
    page: {
      flexDirection: 'row',
      backgroundColor: '#E4E4E4'
    },
    section: {
      margin: 10,
      padding: 10,
      flexGrow: 1
    }
  });

  // Create Document Component
  const MyDocument = () => (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.section}>
          <Text>Section #1</Text>
        </View>
        <View style={styles.section}>
          <Text>Section #2</Text>
        </View>
      </Page>
    </Document>
  );

const App = () => (
  <PDFViewer>
    <MyDocument />
  </PDFViewer>
);

ReactDOM.render(<App />, document.getElementById('root'));
```
5. Run `yarn dev` and try to run it.

_You can make use of [react-pdf REPL](https://react-pdf.org/repl) to share the snippet_

**Expected behavior**
The page should render a PDF.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - React-pdf version ^2.1.1

**Comment by mknml** [comment]
Same issue here! react-pdf repl is disabling server side rendering I read.

**Comment by diegomura** [comment]
Yes. We currently don't support isomorphic rendering in both server and client with the same code

**Comment by diegomura** [comment]
Removing as duplicated https://github.com/diegomura/react-pdf/issues/1815

**Comment by outdatedx** [comment]
> you may want to use dynamic nextjs import to use this package on nextjs. It works for me

Heya Im not really able to import dynamically import it could you send in the code block possibly?
