### ISSUE TITLE
Custom Font Loading Issue on Second+ Attempt

### ISSUE THREAD

**Issue by flaurida** [diegomura/react-pdf#184]
Hi React PDF,

Still love this project! I am loading in custom fonts, and on my first time viewing the PDF it works, however, if I try to open the file again, I get an error relating to my custom font: 
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: ENOENT: no such file or directory, open 'Basetica'`.

This is how I am loading the font, above the stylesheet in my main file:
```
Font.register(`${__dirname}/fonts/Basetica/Basetica-Medium.ttf`, {
  family: 'Basetica',
});
```

And the full stack trace - I wonder if it has to do with fontkit then trying to load the font? Interesting that it doesn't actually trace back to my component file:
```
{ Error: ENOENT: no such file or directory, open 'Basetica'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fontkit.openSync (/Users/lauracressman/Desktop/src/commons/node_modules/fontkit/src/base.js:15:19)
    at Function.PDFFont.open (/Users/lauracressman/Desktop/src/commons/node_modules/pdfkit/js/font.js:14:24)
    at PDFDocument.font (/Users/lauracressman/Desktop/src/commons/node_modules/pdfkit/js/mixins/fonts.js:39:28)
    at Text.setFontFamily (/Users/lauracressman/Desktop/src/commons/node_modules/@react-pdf/core/lib/elements/Text.js:94:17)
    at Text.measureText (/Users/lauracressman/Desktop/src/commons/node_modules/@react-pdf/core/lib/elements/Text.js:119:12)
    at External.data (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/dist/entry-common.js:218:40)
    at Array.eval (eval at buildJSCallerFunction (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/build/Release/nbind.js:1449:328), <anonymous>:1:86)
    at Array.ASM_CONSTS (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/build/Release/nbind.js:557:45)
    at _emscripten_asm_const_iiididi (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/build/Release/nbind.js:565:28)
    at Tg (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/build/Release/nbind.js:3475:134)
    at Rg (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/build/Release/nbind.js:3471:64)
    at Qg (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/build/Release/nbind.js:3468:144)
    at Array.Pg (/Users/lauracressman/Desktop/src/commons/node_modules/yoga-layout/build/Release/nbind.js:3462:44)
```

Thanks!

Sincerely,
Laura

**Comment by diegomura** [comment]
Hi @flaurida !
Have some questions here:

- Before going to the actual issue, why are you loading twice the same font? I would strongly recommend not to do so.

- Then, when you load for the second time, is it from the same file as the first time? or files inside the same hierarchy inside your project?  I'm wondering if `__dirname` can be different the second time and node actually not being able to find the file, as the error says.

**Comment by flaurida** [comment]
Hi @diegomura thanks again for helping! I think the issue is I am loading the font in my server endpoint, so every time it is hit the font loads. I solved it for now by clearing the fonts in the endpoint, but wonder if there isn't a single place in the app that will run the code to load the fonts once and that is it.

**Comment by diegomura** [comment]
Thanks for replying! 
Very interesting. To be honest I never did something like that, just some small tests.
What if you put the `Font.register` call outside your endpoint's callback?

**Comment by flaurida** [comment]
I will try it, just need to figure out exactly where first! Will keep you posted 😊

**Comment by diegomura** [comment]
Thanks @flaurida ! 
Going to close this for the moment, unless you find something that can be fixed on my end. Please submit updates here anyway!

**Comment by diegomura** [comment]
@flaurida I think you will find this very interesting 👆 😄

**Comment by flaurida** [comment]
Awesome thank you so much!!
