### ISSUE TITLE
Hi, i have Problem ,When I run the, yarn example -- fractals,i got this issues 

### ISSUE THREAD

**Issue by YadavSudhakar** [diegomura/react-pdf#185]
TypeError: {} is not a function
    at D:\recatPrinter\react-pdf\packages\react-pdf\node_modules\yoga-layout\build\Release\nbind.js:25:22
    at initAsm (D:\recatPrinter\react-pdf\packages\react-pdf\node_modules\nbind\dist\nbind.js:128:33)
    at D:\recatPrinter\react-pdf\packages\react-pdf\node_modules\nbind\dist\nbind.js:112:13
    at findCompiledModule (D:\recatPrinter\react-pdf\packages\react-pdf\node_modules\nbind\dist\nbind.js:79:13)
    at find (D:\recatPrinter\react-pdf\packages\react-pdf\node_modules\nbind\dist\nbind.js:93:13)
    at Object.init (D:\recatPrinter\react-pdf\packages\react-pdf\node_modules\nbind\dist\nbind.js:104:5)
    at Object.<anonymous> (D:\recatPrinter\react-pdf\packages\react-pdf\node_modules\yoga-layout\sources\entry-node.js:11:17)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\recatPrinter\react-pdf\node_modules\babel-register\lib\node.js:152:7)
Done in 11.38s.

**Comment by dprosper** [comment]
Same issue here as well.

**Comment by diegomura** [comment]
OS? Windows?

**Comment by dprosper** [comment]
Seems to be Windows only, this works on Mac OS.

**Comment by cauu** [comment]
Ubuntu has similar problem:
TypeError: (intermediate value) is not a function
    at /home/nb09/Dev/test/react-pdf/packages/react-pdf/node_modules/yoga-layout/build/Release/nbind.js:25:22
    at initAsm (/home/nb09/Dev/test/react-pdf/packages/react-pdf/node_modules/nbind/dist/nbind.js:128:33)
    at /home/nb09/Dev/test/react-pdf/packages/react-pdf/node_modules/nbind/dist/nbind.js:112:13
    at findCompiledModule (/home/nb09/Dev/test/react-pdf/packages/react-pdf/node_modules/nbind/dist/nbind.js:79:13)
    at find (/home/nb09/Dev/test/react-pdf/packages/react-pdf/node_modules/nbind/dist/nbind.js:93:13)
    at Object.init (/home/nb09/Dev/test/react-pdf/packages/react-pdf/node_modules/nbind/dist/nbind.js:104:5)
    at Object.<anonymous> (/home/nb09/Dev/test/react-pdf/packages/react-pdf/node_modules/yoga-layout/sources/entry-node.js:11:17)
    at Module._compile (module.js:573:32)
    at Module._extensions..js (module.js:582:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/nb09/Dev/test/react-pdf/node_modules/babel-register/lib/node.js:152:7)
Done in 1.57s.

**Comment by diegomura** [comment]
Thanks for reporting it. unfortunately I don't have either an Ubuntu or Windows env set up. I'll try to tackle this soon, but can take awhile. If any of you wants to help to figure out what's going on, help is more than welcome!

**Comment by diegomura** [comment]
Keeping the yoga windows build discussion in #211 . Closing this
