### ISSUE TITLE
Error: unsupported number: Infinity with 2.1.2

### ISSUE THREAD

**Issue by modosc** [diegomura/react-pdf#1853]
**Describe the bug**

i did some more debugging related to the `2.1.2` upgrade and found another issue:
```
  e: Error: unsupported number: Infinity
      at Function.number (repo/node_modules/@react-pdf/pdfkit/lib/pdfkit.cjs.js:260:11)
      at repo/node_modules/@react-pdf/pdfkit/lib/pdfkit.cjs.js:1829:70
      at Array.map (<anonymous>)
      at PDFDocument.transform (repo/node_modules/@react-pdf/pdfkit/lib/pdfkit.cjs.js:1829:49)
      at PDFDocument.translate (repo/node_modules/@react-pdf/pdfkit/lib/pdfkit.cjs.js:1834:17)
      at resolveAspectRatio (repo/node_modules/@react-pdf/render/lib/primitives/renderSvg.js:288:13)
      at renderSvg (repo/node_modules/@react-pdf/render/lib/primitives/renderSvg.js:329:3)
      at renderNode (repo/node_modules/@react-pdf/render/lib/primitives/renderNode.js:75:17)
      at renderChild (repo/node_modules/@react-pdf/render/lib/primitives/renderNode.js:54:12)
      at Array.forEach (<anonymous>)
      at renderChildren (repo/node_modules/@react-pdf/render/lib/primitives/renderNode.js:57:12)
      at renderNode (repo/node_modules/@react-pdf/render/lib/primitives/renderNode.js:76:29)
      at renderChild (repo/node_modules/@react-pdf/render/lib/primitives/renderNode.js:54:12)
      at Array.forEach (<anonymous>)
      at renderChildren (repo/node_modules/@react-pdf/render/lib/primitives/renderNode.js:57:12)
      at renderNode (repo/node_modules/@react-pdf/render/lib/primitives/renderNode.js:76:29)
      at renderChild (repo/node_modules/@react-pdf/render/lib/primitives/renderNode.js:54:12)
      at Array.forEach (<anonymous>)
      at renderChildren (repo/node_modules/@react-pdf/render/lib/primitives/renderNode.js:57:12)
      at renderNode (repo/node_modules/@react-pdf/render/lib/primitives/renderNode.js:76:29)
      at repo/node_modules/@react-pdf/render/lib/index.js:16:36
      at Array.forEach (<anonymous>)
      at Object.render [as default] (repo/node_modules/@react-pdf/render/lib/index.js:15:9)
      at render (repo/node_modules/@react-pdf/renderer/lib/react-pdf.cjs.js:260:41)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async renderToStream (repo/node_modules/@react-pdf/renderer/lib/react-pdf.cjs.js:355:18)
      at async Context.<anonymous> (file:///repo/test/pdf.test.mjs:30:26)
```

i won't have time until next week to find a repro case  but i believe i found the underlying error:

https://github.com/diegomura/react-pdf/blob/9bdb5c934a822340754cd4c892d399f91f6218de/packages/render/src/primitives/renderSvg.js#L226-L236

in our case we're ending up here with `height === 0`, here's the state of other related variables:
```
{
  x: 0,
  width: 100,
  logicalHeight: 80,
  logicalRatio: 1,
  logicalWidth: 80,
  height: 0,
  y: 0
}
```

this error doesn't occur in `2.1.1`. 

**To Reproduce**
todo

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos
 - Browser node
 - React-pdf version 2.1.2

**Comment by diegomura** [comment]
Thanks @modosc . Sorry, but cannot figure out the cause of this only by the provided stack traces. Although it manifests in the render file you shared, the issue is most likely in the layout phase. If you can provide a repro case I promise I'll take a look asap

**Comment by diegomura** [comment]
Is it possible https://github.com/diegomura/react-pdf/issues/1851 fixed this?

**Comment by modosc** [comment]
this seems to be fixed in `2.3.0`, thanks!

**Comment by KilianB** [comment]
We just stumbled upon this again. Can we please reopen the issue. I'll see if it can be reproduced with out data

````
Error unsupported number: Infinity undefined Error: unsupported number: Infinity
    at number (/var/www/api/node_modules/@react-pdf/pdfkit/lib/pdfkit.js:236:15)
    at map (native:1:11)
    at transform (/var/www/api/node_modules/@react-pdf/pdfkit/lib/pdfkit.js:1763:49)
    at resolveAspectRatio (/var/www/api/node_modules/@react-pdf/render/lib/index.js:683:13)
    at renderSvg (/var/www/api/node_modules/@react-pdf/render/lib/index.js:719:3)
    at renderNode (/var/www/api/node_modules/@react-pdf/render/lib/index.js:1904:17)
    at forEach (native:1:11)
    at renderChildren (/var/www/api/node_modules/@react-pdf/render/lib/index.js:1882:12)
    at renderNode (/var/www/api/node_modules/@react-pdf/render/lib/index.js:1905:29)
    at forEach (native:1:11)
````

**Comment by KilianB** [comment]
Our issue was an svg component that was rendered just across a page break. Not the pretties solution but the following patch at least generates the pdf. The image itself was broken but this is better than not generating a pdf at all.

````diff
diff --git a/lib/pdfkit.js b/lib/pdfkit.js
index 24e339f429890bbe1eaf3b08fb18cd1e8e32bbf2..701d52565f1d9da90bb72e3740803239c3607620 100644
--- a/lib/pdfkit.js
+++ b/lib/pdfkit.js
@@ -1,11 +1,11 @@
-import stream from 'stream';
-import zlib from 'zlib';
+import PNG from '@react-pdf/png-js';
+import * as CryptoJS from 'crypto-js/core.js';
 import MD5 from 'crypto-js/md5.js';
 import * as fontkit from 'fontkit';
 import fs from 'fs';
 import _JPEG from 'jay-peg';
-import PNG from '@react-pdf/png-js';
-import * as CryptoJS from 'crypto-js/core.js';
+import stream from 'stream';
+import zlib from 'zlib';
 
 class PDFReference extends stream.Writable {
   constructor(document, id, data) {
@@ -233,7 +233,9 @@ class PDFObject {
     if (n > -1e21 && n < 1e21) {
       return Math.round(n * 1e6) / 1e6;
     }
-    throw new Error(`unsupported number: ${n}`);
+	if (!Number.isFinite(n)) {
+		return 1e6;
+	}
   }
 }
 var PDFObject$1 = PDFObject;

````
