### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by chathu-novade** [diegomura/react-pdf#1995]
**Describe the bug**
I have setup a jest based testing suite. It was working without any issues and after upgrading to the version 3.0.0, I'm getting following error.

```bash
 ● Test suite failed to run

    ReferenceError: TextEncoder is not defined

      1 | 
      2 |
    > 3 | import { Font } from '@react-pdf/renderer';
        | ^
      4 |
      5 | 
      6 |  

      at Object.<anonymous> (../../node_modules/.pnpm/restructure@3.0.0/node_modules/restructure/dist/src/EncodeStream.js:3:21)
      at Object.<anonymous> (../../node_modules/.pnpm/fontkit@2.0.2/node_modules/fontkit/dist/browser.cjs:1:46)
      at Object.<anonymous> (../../node_modules/.pnpm/@react-pdf+font@2.3.0/node_modules/@react-pdf/font/lib/index.cjs.js:11:15)
      at Object.<anonymous> (../../node_modules/.pnpm/@react-pdf+renderer@3.0.0_react@17.0.2/node_modules/@react-pdf/renderer/lib/react-pdf.cjs.js:10:17)
      at Object.<anonymous> (src/utils/index.ts:3:1)
      at Object.<anonymous> (__test__/jest-setup.ts:2:1)
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - React-pdf version [^3.0.0]

**Comment by chathu-novade** [comment]
Seems for previous version I have setup the jestEnviornment as 'jsdom'

Once I set it to 'node' tests started to work. But I'm now getting following error

```bash

(node:31874) V8: /Users/user/project/node_modules/.pnpm/@react-pdf+yoga@3.0.0/node_modules/@react-pdf/yoga/src/build/Release/nbind.js:1781 Linking failure in asm.js: Unexpected stdlib member
```

**Comment by chathu-novade** [comment]
Seems it was there earlier too. https://github.com/diegomura/react-pdf/issues/1627
