### ISSUE TITLE
<Image /> throws error when using in NextJS with swcMinify

### ISSUE THREAD

**Issue by MishaFrenkman** [diegomura/react-pdf#2063]
**Describe the bug**
I'm using react-pdf with nextjs (v12). When running in dev mode everything works as expected.
When building the app for production with `swcMinfiy: true` in `next.config.js` I'm getting the following error on the <Image /> component 

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'width')
    at drawImage (_app-4582e1627b46c737.js:115:440420)
    at renderImage (_app-4582e1627b46c737.js:115:440829)
    at renderNode (_app-4582e1627b46c737.js:115:452973)
    at d (_app-4582e1627b46c737.js:115:452461)
    at Array.forEach (<anonymous>)
    at renderChildren (_app-4582e1627b46c737.js:115:452482)
    at renderNode (_app-4582e1627b46c737.js:115:452985)
    at d (_app-4582e1627b46c737.js:115:452461)
    at Array.forEach (<anonymous>)
    at renderChildren (_app-4582e1627b46c737.js:115:452482)
```

Using `swcMinify: false` it works as expected. 
But swc is considered best practice/ stable and is on per default starting Nextjs v13. So leaving it off can't be the solution.

**To Reproduce**
as described above

**Expected behavior**
Should not throw error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS M1
 - Browser: Chrome
 - Nextjs v12
 - React v18
 - React-pdf v.3.0.0

**Comment by jacob-mako** [comment]
Hitting this same issue as well. Any leads? Workaround from @MishaFrenkman seemed to do the trick

**Comment by mbhadra23** [comment]
Hi @w3ichen - I was able to get rid of the same error using your solution, however, I get a different warning - "Not valid image extension".
Can you provide an example of the Url object that you are passing as dataString? I suspect I may have a format error. I have tried all permutation combinations I can think of.

Here is what I am doing :
      <Text>image has a uri</Text>
       <Image src={{ uri: { imgUrl }, method: "GET", headers: { "Cache-Control": "no-cache" }, body: "" }} style={styles.Logo} />

imgUrl =
"image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAW8AAACmCAYAAAAVrA7cAAAAAXNSR0IArs4c6QAAIABJREFUeF7tnQmYW2W5x//vycx02k5ZhLohj2WZJCNXQeXRW6/33rrQJAW9LpMoqwVyAohCQRQV1IIgIkgLKKVJWkoBkU5ZLktzMhXpVWTxwlXgQnNSlnJFZCtrl+nM5Lz3OYGkmWmmk+UkOefkPc/Tp32S73uX33v6z5cv3/k+glxCQAgIASHgOALkuIglYCEgBISAEICIt9wEQkAICAEHEhDxdmDRJGQhIASEgIi33.."

**Comment by w3ichen** [comment]
Hi @mbhadra23, with the `dataString`, mine looks like this:
```javascript
<Image src={{ uri: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJQAAACU", method: "GET", headers: {}, body: "" }} style={{ width: "200px" }} />
``` 

I hope that helps :)

**Comment by mbhadra23** [comment]
Thank you. Yes, I have also tried this but it still doesn't render for me. I am now thinking if there is a limit to the size of the image.
