### ISSUE TITLE
renderToFile errors with "Could not resolve font", but I can get the font with Font.getFont

### ISSUE THREAD

**Issue by dustin-rcg** [diegomura/react-pdf#2117]
**Describe the bug**
I am using react-pdf in Node with a yarn pnp project. I have a very basic example project that uses a font family that I registered. When I render the PDF using `renderToFile`, I always get the error `Could not resolve font for open_sans, fontWeight 400`. However, if I get the font by calling `Font.getFont({ fontFamily: "open_sans", fontWeight: 400 })` in my code, the font is returned. After looking at the react-pdf source code related to fonts, I am wondering if the code that is run by `renderToFile` is using a different instance of the FontStore object than my code, resulting the in font not being found. If that is true, I don't know how to use this library without being able to pass the FontStore instance into the render function.

**To Reproduce**
I am registering the font like this:
```
import { Font, renderToFile, renderToStream } from "@react-pdf/renderer";

Font.register({
      family: "open_sans",
      fonts: [
        {
          src: "/[snip]/opensans-regular.ttf",
          fontWeight: 400,
        },
      ],
    });

    await Font.load({ fontFamily: "open_sans", fontWeight: 400 });
```

After this, I can check that the font is there:
```
console.log(
    "GET FONT ->",
    Font.getFont({ fontFamily: "open_sans", fontWeight: 400 })
  );
```

This returns:
```
GET FONT -> FontSource {
  src: '/[snip]/opensans-regular.ttf',
  fontFamily: 'open_sans',
  fontStyle: 'normal',
  fontWeight: 400,
  data: $0a8ef2660a6ce4b6$export$2e2bcd8739ae039 {
    type: 'TTF',
    defaultLanguage: null,
    stream: $8ae20583b93e4933$export$c18b354bac7948e9 {
      buffer: <Buffer 00 01 00 00 00 13 01 00 00 04 00 30 44 53 49 47 9e 12 44 1d 00 03 3b 9c 00 00 15 74 47 44 45 46 00 26 03 af 00 03 37 7c 00 00 00 1e 47 50 4f 53 0b 37 ... 217310 more bytes>,
      view: [DataView],
      pos: 316,
      length: 217360
    },
    variationCoords: null,
    _directoryPos: 0,
    _tables: {},
    _glyphs: {},
    directory: {
      tag: '\x00\x01\x00\x00',
      numTables: 19,
      searchRange: 256,
      entrySelector: 4,
      rangeShift: 48,
      tables: [Object]
    }
  },
  options: { family: 'open_sans' },
  loadResultPromise: Promise { undefined }
}
```

I have a single basic page I am trying to render.

```
export function TitlePage({ sections, section }: Props) {
  // I put this here again to verify that the font is there
  console.log(
    "GET FONT ->",
    Font.getFont({ fontFamily: "open_sans", fontWeight: 400 })
  );

  return (
    <Page
      size="LETTER"
      style={{
        padding: "100 20 70 20",
        fontFamily: "open_sans",
      }}
    >
      <View>
        <View>
          <Text style={STYLES.report_title}>{section.title}</Text>
        </View>
      </View>
    </Page>
  );
}

export function Report({ sections, preferences }: Props) {
  const { author, creator, keywords, producer, subject, title } =
    preferences.metadata;

  return (
    <Document
      title={title}
      author={author}
      subject={subject}
      creator={creator}
      keywords={keywords}
      producer={producer}
    >
      {sections.all.map((section, isection) => {
        switch (section.key) {
          case "title_page":
            return (
              <TitlePage
                key={isection}
                sections={sections}
                section={section as SectionFrontMatter}
              />
            );
            
            // ... snip
}
```

I try to render this with
```
async renderToFile(path: string) {
    await this.registerFonts();
    return await renderToFile(
      <Report sections={this.sections} preferences={this.preferences} />,
      path
    );
  }
```

But I always get this error:
```
/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-yoga-npm-3.0.0-e6e7b2a151-d854112020.zip/node_modules/@react-pdf/yoga/src/build/Release/nbind.js:53
        throw ex;
        ^

Error: Could not resolve font for open_sans, fontWeight 400
    at Font.resolve (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-font-npm-2.3.1-02099a02f0-f3b9db3cb0.zip/node_modules/@react-pdf/font/lib/index.cjs.js:281:13)
    at FontStore.getFont (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-font-npm-2.3.1-02099a02f0-f3b9db3cb0.zip/node_modules/@react-pdf/font/lib/index.cjs.js:341:30)
    at _callee$ (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-font-npm-2.3.1-02099a02f0-f3b9db3cb0.zip/node_modules/@react-pdf/font/lib/index.cjs.js:362:25)
    at tryCatch (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.20.6-ef7cda3b78-42a8504db2.zip/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.20.6-ef7cda3b78-42a8504db2.zip/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.20.6-ef7cda3b78-42a8504db2.zip/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.20.6-ef7cda3b78-42a8504db2.zip/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.20.6-ef7cda3b78-42a8504db2.zip/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at /Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.20.6-ef7cda3b78-42a8504db2.zip/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
```

**Expected behavior**

Based on the output of GET FONT, I can see that the code should return an exact match here: https://github.com/diegomura/react-pdf/blob/master/packages/font/src/font.js#L110
However, for some reason, the code go all the way to the error message here: https://github.com/diegomura/react-pdf/blob/master/packages/font/src/font.js#L140

If the renderToFile code is using the same instance of the FontStore as my code, this error cannot happen. So, it seems to be using a different instance.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.6 (21G115)
 - Browser: N/A
 - React-pdf version: 3.0.1

**Comment by dustin-rcg** [comment]
One of the import had the style `fontStyle: "bold"` which is invalid
