### ISSUE TITLE
Incompatible with vite?

### ISSUE THREAD

**Issue by AndreiTS** [diegomura/react-pdf#2145]
**Describe the bug**
I'm migrating my project from CRA to vite.
When I try to run with vite I'm receiving the following error:

```
Could not resolve "file-loader!pdfjs-dist/build/pdf.worker"

    node_modules/react-pdf/dist/esm/entry.webpack.js:3:24:
      3 │ import pdfjsWorker from 'file-loader!pdfjs-dist/build/pdf.worker';
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "file-loader!pdfjs-dist/build/pdf.worker" as external to exclude it from the
  bundle, which will remove this error.
```

```
Error: Build failed with 1 error:
node_modules/react-pdf/dist/esm/entry.webpack.js:3:24: ERROR: Could not resolve "file-loader!pdfjs-dist/build/pdf.worker"
    at failureErrorWithLog (/home/andrei/Documentos/GitHub/MercurioWebFrontend/node_modules/esbuild/lib/main.js:1604:15)
    at /home/andrei/Documentos/GitHub/MercurioWebFrontend/node_modules/esbuild/lib/main.js:1056:28
    at runOnEndCallbacks (/home/andrei/Documentos/GitHub/MercurioWebFrontend/node_modules/esbuild/lib/main.js:1476:61)
    at buildResponseToResult (/home/andrei/Documentos/GitHub/MercurioWebFrontend/node_modules/esbuild/lib/main.js:1054:7)
    at /home/andrei/Documentos/GitHub/MercurioWebFrontend/node_modules/esbuild/lib/main.js:1166:14
    at responseCallbacks.<computed> (/home/andrei/Documentos/GitHub/MercurioWebFrontend/node_modules/esbuild/lib/main.js:701:9)
    at handleIncomingPacket (/home/andrei/Documentos/GitHub/MercurioWebFrontend/node_modules/esbuild/lib/main.js:756:9)
    at Socket.readFromStdout (/home/andrei/Documentos/GitHub/MercurioWebFrontend/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 24,
        file: 'node_modules/react-pdf/dist/esm/entry.webpack.js',
        length: 41,
        line: 3,
        lineText: "import pdfjsWorker from 'file-loader!pdfjs-dist/build/pdf.worker';",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "file-loader!pdfjs-dist/build/pdf.worker" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "file-loader!pdfjs-dist/build/pdf.worker"'
    }
  ],
  warnings: []
}
```

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Run a project with vite and react-pdf
2. See the error

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser none
 - React-pdf version 6.2.2

**Comment by Krzyku** [comment]
It's problem with [react-pdf](https://github.com/wojtekmaj/react-pdf) library, not `@react-pdf/renderer` ;)

**Comment by AndreiTS** [comment]
oh sorry
