### ISSUE TITLE
Bug in react-pdf layout: Cannot read properties of undefined (reading 'height') at splitNodes

### ISSUE THREAD

**Issue by dustin-rcg** [diegomura/react-pdf#2234]
**Describe the bug**

It seems to be related to the complexity of the document. I have been implementing the rendering of a json-based template, which just recursively visits the json document and translates that into react components that react-pdf renders. As I have been implementing the components and adding them to the component factory, I have reached a point where react-pdf seems to choke on the document.

If I go one-by-one and change the component factory to just return a null component (`() => null`) for each component, but don't decrease the number of components, I continue to see this error.  If I start _removing_ components from the component factory, to decrease the number of components, the error goes away.

I will add that I am porting existing code to react-pdf, and the PDF generated by the old code is only 58 pages long, and I have only implemented half of the sections. So, the document is not long in terms of pages.

**To Reproduce**

Unfortunately, this seems to be related to the complexity of the document and a simple reproduction is not possible.

**Expected behavior**

I should not get this internal error. I should be able to continue defining the components for the component factory.

**Screenshots**

```
/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-layout-npm-3.5.0-b32570275c-752e759737.zip/node_modules/@react-pdf/layout/lib/index.cjs.js:3158
    var nodeHeight = child.box.height;
                               ^
TypeError: Cannot read properties of undefined (reading 'height')
    at splitNodes (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-layout-npm-3.5.0-b32570275c-752e759737.zip/node_modules/@react-pdf/layout/lib/index.cjs.js:3158:32)
    at splitPage (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-layout-npm-3.5.0-b32570275c-752e759737.zip/node_modules/@react-pdf/layout/lib/index.cjs.js:3293:21)
    at paginate (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-layout-npm-3.5.0-b32570275c-752e759737.zip/node_modules/@react-pdf/layout/lib/index.cjs.js:3341:22)
    at resolvePagination (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-layout-npm-3.5.0-b32570275c-752e759737.zip/node_modules/@react-pdf/layout/lib/index.cjs.js:3365:20)
    at _callee$ (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-fns-npm-2.0.1-bc12617968-cc56f63286.zip/node_modules/@react-pdf/fns/lib/index.cjs.js:68:23)
    at tryCatch (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.21.0-c4ef698c89-7b33e25bfa.zip/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.21.0-c4ef698c89-7b33e25bfa.zip/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.21.0-c4ef698c89-7b33e25bfa.zip/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.21.0-c4ef698c89-7b33e25bfa.zip/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.21.0-c4ef698c89-7b33e25bfa.zip/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
```

**Desktop (please complete the following information):**
 - OS: MacOD Ventura 13.2.1
 - This is a nodeJS-rendered project using `renderToFile`
 - NodeJS version: v16.17.0
 - React-pdf version: @react-pdf/renderer 3.1.7

**Comment by dustin-rcg** [comment]
I am still getting this internal error from @react-pdf/layout after upgrading to @react-pdf/renderer 3.1.9. Any ideas @diegomura ?

```
/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-layout-npm-3.6.0-bb4d166ea9-65169700d8.zip/node_modules/@react-pdf/layout/lib/index.cjs.js:3159
    var nodeHeight = child.box.height;
                               ^
TypeError: Cannot read properties of undefined (reading 'height')
    at splitNodes (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-layout-npm-3.6.0-bb4d166ea9-65169700d8.zip/node_modules/@react-pdf/layout/lib/index.cjs.js:3159:32)
    at splitPage (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-layout-npm-3.6.0-bb4d166ea9-65169700d8.zip/node_modules/@react-pdf/layout/lib/index.cjs.js:3294:21)
    at paginate (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-layout-npm-3.6.0-bb4d166ea9-65169700d8.zip/node_modules/@react-pdf/layout/lib/index.cjs.js:3342:22)
    at resolvePagination (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-layout-npm-3.6.0-bb4d166ea9-65169700d8.zip/node_modules/@react-pdf/layout/lib/index.cjs.js:3366:20)
    at _callee$ (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@react-pdf-fns-npm-2.0.1-bc12617968-cc56f63286.zip/node_modules/@react-pdf/fns/lib/index.cjs.js:68:23)
    at tryCatch (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.21.0-c4ef698c89-7b33e25bfa.zip/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.21.0-c4ef698c89-7b33e25bfa.zip/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.21.0-c4ef698c89-7b33e25bfa.zip/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.21.0-c4ef698c89-7b33e25bfa.zip/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/dustin.bortner/code/repos/RCG-Sirius/async-workers/.yarn/cache/@babel-runtime-npm-7.21.0-c4ef698c89-7b33e25bfa.zip/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
```

**Comment by dustin-rcg** [comment]
OK, I figured out the affected section and found that the root component was not wrapped in a `<Page>`, which was breaking the following layout code:
https://github.com/diegomura/react-pdf/blob/72b5e172e4fd963216373c550228a0075adf6c76/packages/layout/src/page/getWrapArea.js#L3-L7

**Comment by zeeshanmazhar** [comment]
Hi, I am facing the same issue, not able to resolve the issue, can anyone let me know the permanent solution for this? Thanks.
