### ISSUE TITLE
Getting this error while passing large objects of array to pdf component

### ISSUE THREAD

**Issue by kkg0** [diegomura/react-pdf#2337]
I'm Passing Server Data from App.js to PDF Component using props.

TypeError: Cannot read properties of null (reading 'xCoordinate')
    at $c96c93587d49c14d$export$2e2bcd8739ae039.getAnchor (GPOSProcessor.js:289:1)
    at $c96c93587d49c14d$export$2e2bcd8739ae039.applyAnchor (GPOSProcessor.js:276:1)
    at $c96c93587d49c14d$export$2e2bcd8739ae039.applyLookup (GPOSProcessor.js:179:1)
    at $c96c93587d49c14d$export$2e2bcd8739ae039.applyLookups (OTProcessor.js:203:1)
    at $c96c93587d49c14d$export$2e2bcd8739ae039.applyFeatures (OTProcessor.js:184:1)
    at $c96c93587d49c14d$export$2e2bcd8739ae039.applyFeatures (GPOSProcessor.js:309:1)
    at $94d7a73bd2edfc9a$export$2e2bcd8739ae039.process (ShapingPlan.js:111:1)
    at $a62492810de27e3d$export$2e2bcd8739ae039.position (OTLayoutEngine.js:66:1)
    at $4c0a7fa5df7a9ab1$export$2e2bcd8739ae039.position (LayoutEngine.js:96:1)
    at $4c0a7fa5df7a9ab1$export$2e2bcd8739ae039.layout (LayoutEngine.js:71:1)

TypeError: Cannot read properties of null (reading 'xCoordinate')
    at r.value (main.00226054.js:1:2994209)
    at r.value (main.00226054.js:1:2993981)
    at r.value (main.00226054.js:1:2992675)
    at r.value (main.00226054.js:1:2905234)
    at r.value (main.00226054.js:1:2904801)
    at r.value (main.00226054.js:1:2994576)
    at e.value (main.00226054.js:1:2896994)
    at e.value (main.00226054.js:1:2996778)
    at e.value (main.00226054.js:1:2999077)
    at e.value (main.00226054.js:1:2998688)

**Comment by kkg0** [comment]
I have resolved this isssue after lot of debugging that Custom Gujarati Font is causing this issue for large data. After changing the font it works like charm !! 

Also Discovered the custom function to download PDF on button Click 
`  const DownloadPDF = async () => {
    setPDFLoading(true);
    const doc = <PDF data={data} />;
    const asPdf = pdf([]);
    asPdf.updateContainer(doc);
    const blob = await asPdf.toBlob();
    saveAs(blob, "your_pdf.pdf"); // for Save As you need file-saver library
    setPDFLoading(false);
  };`

Hope this helps some one ...

**Comment by IntelKancharala** [comment]
Could you please share which font you had used to fix this? and which was causing the problem?
