### ISSUE TITLE
Unable to render in Next.js 13 app directory route handler

### ISSUE THREAD

**Issue by joshuajaco** [diegomura/react-pdf#2350]
**Describe the bug**

Using `renderToBuffer` in a Next.js 13 app directory route handler throws: `TypeError: ba.Component is not a constructor`.
It works as expected when using a route handler inside of the pages directory instead.

<details>
<summary>full output</summary>

```
- warn ./node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/Users/foo/react-pdf-nextjs/node_modules/node-fetch/lib'

Import trace for requested module:
./node_modules/node-fetch/lib/index.js
./node_modules/cross-fetch/dist/node-ponyfill.js
./node_modules/@react-pdf/font/lib/index.cjs.js
./node_modules/@react-pdf/renderer/lib/react-pdf.cjs.js
./src/app/api/app.pdf/route.tsx
- error TypeError: ba.Component is not a constructor
    at $$$reconciler (webpack-internal:///(sc_server)/./node_modules/@react-pdf/renderer/lib/react-pdf.cjs.js:631:50)
    at createRenderer (webpack-internal:///(sc_server)/./node_modules/@react-pdf/renderer/lib/react-pdf.cjs.js:3889:12)
    at pdf (webpack-internal:///(sc_server)/./node_modules/@react-pdf/renderer/lib/react-pdf.cjs.js:3997:28)
    at _callee$ (webpack-internal:///(sc_server)/./node_modules/@react-pdf/renderer/lib/react-pdf.cjs.js:4189:32)
    at tryCatch (webpack-internal:///(sc_server)/./node_modules/@babel/runtime/helpers/regeneratorRuntime.js:36:25)
    at Generator.eval (webpack-internal:///(sc_server)/./node_modules/@babel/runtime/helpers/regeneratorRuntime.js:120:30)
    at Generator.eval [as next] (webpack-internal:///(sc_server)/./node_modules/@babel/runtime/helpers/regeneratorRuntime.js:64:29)
    at asyncGeneratorStep (webpack-internal:///(sc_server)/./node_modules/@babel/runtime/helpers/asyncToGenerator.js:4:28)
    at _next (webpack-internal:///(sc_server)/./node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:17)
    at eval (webpack-internal:///(sc_server)/./node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:13)
    at new Promise (<anonymous>)
    at eval (webpack-internal:///(sc_server)/./node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:16)
    at renderToStream (webpack-internal:///(sc_server)/./node_modules/@react-pdf/renderer/lib/react-pdf.cjs.js:4202:21)
    at renderToBuffer (webpack-internal:///(sc_server)/./node_modules/@react-pdf/renderer/lib/react-pdf.cjs.js:4235:12)
    at GET (webpack-internal:///(sc_server)/./src/app/api/app.pdf/route.tsx:14:93)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:265:43)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/lib/trace/tracer.js:111:36)
    at NoopContextManager.with (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:360:30)
    at ContextAPI.with (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:30:58)
    at NoopTracer.startActiveSpan (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:953:34)
    at ProxyTracer.startActiveSpan (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:993:36)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/lib/trace/tracer.js:100:107)
    at NoopContextManager.with (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:360:30)
    at ContextAPI.with (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:30:58)
    at NextTracerImpl.trace (webpack-internal:///(sc_server)/./node_modules/next/dist/server/lib/trace/tracer.js:100:32)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:253:53)
    at AsyncLocalStorage.run (node:async_hooks:330:14)
    at Object.wrap (webpack-internal:///(sc_server)/./node_modules/next/dist/server/async-storage/static-generation-async-storage-wrapper.js:41:24)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:207:97)
    at AsyncLocalStorage.run (node:async_hooks:330:14)
    at Object.wrap (webpack-internal:///(sc_server)/./node_modules/next/dist/server/async-storage/request-async-storage-wrapper.js:77:24)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:206:75)
    at AsyncLocalStorage.run (node:async_hooks:330:14)
    at AppRouteRouteModule.execute (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:203:56)
    at AppRouteRouteModule.handle (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:326:41)
    at RouteHandlerManager.handle (/Users/foo/react-pdf-nextjs/node_modules/next/dist/server/future/route-handler-managers/route-handler-manager.js:28:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doRender (/Users/foo/react-pdf-nextjs/node_modules/next/dist/server/base-server.js:996:38)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/Users/foo/react-pdf-nextjs/node_modules/next/dist/server/base-server.js:1182:28)
    at async /Users/foo/react-pdf-nextjs/node_modules/next/dist/server/response-cache/index.js:99:36
```
</details>

**To Reproduce**

- Visit https://react-pdf-nextjs-issue.vercel.app/
- Click the "Download PDF from app directory" link and see it not working
- Click the "Download PDF from pages directory" link and see it working

The full reproduction code can be found [here](https://github.com/joshuajaco/react-pdf-nextjs-issue)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - React-pdf version: 3.1.12

**Comment by joshuajaco** [comment]
The issue seems to be that next bundles everything in the app directory using "react-server" mode where [react only exports a subset](https://github.com/facebook/react/blob/fc801116c80b68f7ebdaf66ac77d5f2dcd9e50eb/packages/react/package.json#L24).
This subsert does not contain the `Component` export which `react-reconciler` tries to access, leading to the above mentioned error.

As a temporary workaround I've published [a fork](https://github.com/joshuajaco/react-pdf-bundled/pull/1) that prebundles react, circumventing the problematic behavior.

**Comment by ThomasMcFarlane** [comment]
@joshuajaco - should this workaround still be functional?
I've tried pulling https://github.com/joshuajaco/react-pdf-nextjs-issue/tree/use-fork to test but it still surfaces the same error.

**Comment by Ionito** [comment]
Oh, thanks good I found this.

**Comment by sigma-andex** [comment]
For anyone stumbling upon this since Next.js 13 changed the route handlers: I was able to get this running in a Next.js route using:
```typescript
export const GET: NextApiHandler = async (req, res) => {

  const pdfStream: NodeJS.ReadableStream = await ReactPDF.renderToStream(
    <MyDocument />
  );
  const webStream = Readable.toWeb(new Readable().wrap(pdfStream));
  return new Response(webStream as ReadableStream, {
    headers: { "Content-Type": "application/pdf" },
  });
};
```
Not sure if this is the best way, happy to hear about better ways to do this!

**Comment by charanjit-singh** [comment]
> For anyone stumbling upon this since Next.js 13 changed the route handlers: I was able to get this running in a Next.js route using:
> 
> ```ts
> export const GET: NextApiHandler = async (req, res) => {
> 
>   const pdfStream: NodeJS.ReadableStream = await ReactPDF.renderToStream(
>     <MyDocument />
>   );
>   const webStream = Readable.toWeb(new Readable().wrap(pdfStream));
>   return new Response(webStream as ReadableStream, {
>     headers: { "Content-Type": "application/pdf" },
>   });
> };
> ```
> 
> Not sure if this is the best way, happy to hear about better ways to do this!

Didn't work

**Comment by tjhoo** [comment]
@charanjit-singh It is working for me.
```javascript
import {
  Document,
  Page,
  renderToBuffer,
} from "@joshuajaco/react-pdf-renderer-bundled";
import { NextResponse } from "next/server";

export async function GET(request: Request) {
  const buffer = await renderToBuffer(
    <Document>
      <Page size="A4"></Page>
    </Document>,
  );

  return new NextResponse(buffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="app.pdf"`,
    },
  });
}
```
@joshuajaco this is an issue of Next.js 13 or React? I wish we can mentioned [the fork](https://github.com/joshuajaco/react-pdf-bundled/pull/1) in the quick start guide to make it clear to the developers developing Next.js application.

**Comment by charanjit-singh** [comment]
Thank you, but I managed to get it done using:

```typescript
   const readableStream = await generateInvoicePDF(invoice);
    const chunks = [];
    for await (const chunk of readableStream) {
        chunks.push(
            typeof chunk === "string" ? Buffer.from(chunk) : chunk
        );
    }
    const buffer = Buffer.concat(chunks);

    return new Response(buffer, {
        headers: {
            "Content-Type": "application/pdf"
        }
    });
```

where
```typescript
import { Page, Text, View, Document, renderToStream, Image } from '@joshuajaco/react-pdf-renderer-bundled';

const generateInvoicePDF = async (invoice: Invoice) => {
    const pdfStream = await renderToStream(<InvoicePDF invoice={invoice} />);
    return pdfStream;
};

```

**Comment by jb-thery** [comment]
Utilizing @joshuajaco/react-pdf-renderer-bundled is effective, but it would be great if these issues were addressed in the official repository.

**Comment by ramonmalcolm10** [comment]
Any luck addressing this issue?

**Comment by stabildev** [comment]
Will this be solved?

**Comment by SalihColak** [comment]
Any updates yet?

**Comment by bordeo** [comment]
You can resolve adding `@react-pdf/renderer` to `transpilePackages` in `next.config.js`
```js
const nextConfig = {
  transpilePackages: ['@react-pdf/renderer'],
}
```

**Comment by Dru1DD** [comment]
> I made `@react-pdf/renderer` works on app route page adding `'use client'` on top of page and adding `@react-pdf/renderer` to `transpilePackages` in `next.config.js`
> 
> ```js
> const nextConfig = {
>   transpilePackages: ['@react-pdf/renderer'],
> }
> ```

That's good idea, but it still doesn't work. For me, don't(

**Comment by Dru1DD** [comment]
I have created page api, in Next Js even when you use App Router you can create Page Api Folder and there it works.

pages/api/ - it's my solution even in App Router

**Comment by wojtekmaj** [comment]
The reason you're getting `ba.Component()` is not a constructor is because Next.js opted for a (ridiculous) decision to transparently replace your version of React with `18.3.0-canary-8c8ee9ee6-20231026` (sic!!!) if you happen to use App Router. This version notably missed `React.Component`.

To fix this issue on our side, we would need to drop `react-reconciler` dependency altogether or… update it to `0.30.0-canary`, but this brings in a couple of breaking changes we would need to deal with.

**Comment by stachuuu93** [comment]
Adding this to next.config.js solves issue for me:
`const nextConfig = {
  experimental: {
    serverComponentsExternalPackages: ['@react-pdf/renderer'],
  }
};`

**Comment by omzi** [comment]
Thanks for the update @stachuuu93! It worked perfectly for me :).

**Comment by tjhoo** [comment]
and this should be mentioned in the documentation?

**Comment by wojtekmaj** [comment]
Fixed in Next.js 14.1.1-canary.32 (available tomorrow) 🎉

**Comment by ramonmalcolm10** [comment]
> Adding this to next.config.js solves issue for me:
> 
> ```js
> const nextConfig = {
>   experimental: {
>     serverComponentsExternalPackages: ['@react-pdf/renderer'],
>   }
> };
> ```

Getting this error when I try to include a image in a PDF and it work fine with ```@joshuajaco/react-pdf-renderer-bundled```. Not sure which other packages need to be included in the ```serverComponentsExternalPackages```

```bash
node_modules/yoga-layout/binaries/wasm-async-node.js:11
process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",function(a){throw a;});g.inspect=function(){return"[Emscripten Module object]"};var ia=g.print||console.log.bind(console),v=g.printErr||console.warn.bind(console);Object.assign(g,ba);ba=null;var ja;g.wasmBinary&&(ja=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&w("no native wasm support detected");var ka,la=!1;
                                           ^

TypeError: PNG is not a constructor
    at new PNGImage
```

**Comment by winsvold** [comment]
[next 14.2 is](https://nextjs.org/blog/next-14-2) is out now, seems like rendering pdf in app-folder route works out of the box now 🎉
