### ISSUE TITLE
How can I solve that

### ISSUE THREAD

**Issue by tgmarinho** [diegomura/react-pdf#244]
I tried installing the dependency on my project but I got this error message, and I do not know how to solve it.

Someone can help me, please? Thanks!

My SO: Linux Deepin 15.5
 **uname -a**
**_Linux tgmarinho-PC 4.14.0-deepin2-amd64 #1 SMP PREEMPT Deepin 4.14.12-2 (2018-01-06) x86_64 GNU/Linux_**

tgmarinho@tgmarinho-PC:~/Development/shalomapp$ **yarn add @react-pdf/core**
yarn add v1.7.0
info No lockfile found.
[1/4] Resolving packages...
warning @codeftw/future-web-graphql-date-time-resolver > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning bcrypt@1.0.3: bcrypt < v2.0.0 is susceptible to bcrypt wrap-around bug. Upgrade to bcrypt >= v2.0.0 for improved support for newer bcrypt hashes
warning material-ui-icons@1.0.0-beta.36: Use @material-ui/icons instead
warning material-ui@1.0.0-beta.47: You can now upgrade to @material-ui/core
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > material-ui-pickers@1.0.0-rc.10" has unmet peer dependency "classnames@^2.2.5".
warning " > material-ui-pickers@1.0.0-rc.10" has unmet peer dependency "@material-ui/core@^1.0.0-rc.0".
warning " > react-google-maps@9.4.5" has unmet peer dependency "@types/googlemaps@^3.0.0".
warning " > react-google-maps@9.4.5" has unmet peer dependency "@types/markerclustererplus@^2.1.29".
warning " > react-google-maps@9.4.5" has unmet peer dependency "@types/react@^15.0.0 || ^16.0.0".
[4/4] Building fresh packages...
[-/4] ⢀ waiting...
[2/4] ⢀ bcrypt
[-/4] ⢀ waiting...
error /home/tgmarinho/Development/shalomapp/node_modules/yoga-layout: Command failed.
Exit code: 1
Command: npm run build:node
Arguments: 
Directory: /home/tgmarinho/Development/shalomapp/node_modules/yoga-layout
Output:
> yoga-layout@1.9.3 build:node /home/tgmarinho/Development/shalomapp/node_modules/yoga-layout
> npm run copy-sources && autogypi && node-gyp configure build

> yoga-layout@1.9.3 copy-sources /home/tgmarinho/Development/shalomapp/node_modules/yoga-layout
> ! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)

make: Entering directory '/home/tgmarinho/Development/shalomapp/node_modules/yoga-layout/build'
  COPY Release/obj.target/nbind/geni/symbols.txt
  CXX(target) Release/obj.target/nbind/sources/yoga/Utils.o
make: g++: Command not found
make: *** [Release/obj.target/nbind/sources/yoga/Utils.o] Error 127
nbind.target.mk:141: recipe for target 'Release/obj.target/nbind/sources/yoga/Utils.o' failed
make: Leaving directory '/home/tgmarinho/Development/shalomapp/node_modules/yoga-layout/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.0-deepin2-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/tgmarinho/Development/shalomapp/node_modules/yoga-layout
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yoga-layout@1.9.3 build:node: `npm run copy-sources && autogypi && node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yoga-layout@1.9.3 build:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

tgmarinho@tgmarinho-PC:~/Development/shalomapp$

**Comment by tgmarinho** [comment]
error /home/tgmarinho/Development/shalomapp/node_modules/yoga-layout: Command failed.

**Comment by tgmarinho** [comment]
I create a simple project, just "npm init" and "yarn add @react-pdf/core", so I got the message:

yarn add @react-pdf/core
yarn add v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@react-pdf/core > react-reconciler@0.7.0" has unmet peer dependency "react@^16.0.0".
warning " > @react-pdf/core@0.7.6" has unmet peer dependency "react@^16.0.0".
[4/4] Building fresh packages...
error /home/tgmarinho/Development/teste/node_modules/yoga-layout: Command failed.
Exit code: 1
Command: npm run build:node
Arguments: 
Directory: /home/tgmarinho/Development/teste/node_modules/yoga-layout
Output:
> yoga-layout@1.9.3 build:node /home/tgmarinho/Development/teste/node_modules/yoga-layout
> npm run copy-sources && autogypi && node-gyp configure build


> yoga-layout@1.9.3 copy-sources /home/tgmarinho/Development/teste/node_modules/yoga-layout
> ! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)

make: Entering directory '/home/tgmarinho/Development/teste/node_modules/yoga-layout/build'
  COPY Release/obj.target/nbind/geni/symbols.txt
  CXX(target) Release/obj.target/nbind/sources/yoga/Utils.o
make: g++: Command not found
nbind.target.mk:141: recipe for target 'Release/obj.target/nbind/sources/yoga/Utils.o' failed
make: Leaving directory '/home/tgmarinho/Development/teste/node_modules/yoga-layout/build'
make: *** [Release/obj.target/nbind/sources/yoga/Utils.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.0-deepin2-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/tgmarinho/Development/teste/node_modules/yoga-layout
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yoga-layout@1.9.3 build:node: `npm run copy-sources && autogypi && node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yoga-layout@1.9.3 build:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tgmarinho/.npm/_logs/2018-06-16T01_08_32_586Z-debug.log
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by diegomura** [comment]
Check out this issue: https://github.com/diegomura/react-pdf/issues/225

**Comment by tgmarinho** [comment]
I checked it, but that's don't figure it out my problem. Thanks for while!

**Comment by ferdinandsalis** [comment]
Hey @tgmarinho it seems that you version of linux does not have `g++` installed as stated in the error message,
```
make: g++: Command not found
```
Does installing `g++` with your linux distro package manager solve the problem?

**Comment by tgmarinho** [comment]
@ferdinandsalis  my notebook doesn't work well, I did reinstall of OS, I'll try that. Thanks!

**Comment by tgmarinho** [comment]
@ferdinandsalis @diegomura thanks, my problem is done!

**Comment by luskin** [comment]
I don't believe this is solved our team is running into this error and can't install the repo.

**Comment by atherdon** [comment]
me too. Maybe @diegomura we should give up yoga or at least have some other option?

**Comment by GreenRidingHood** [comment]
In my case I downgraded node 13 to 11 ..
