### ISSUE TITLE
v3.3.1 crashes deep in pdfkit

### ISSUE THREAD

**Issue by EvHaus** [diegomura/react-pdf#2533]
**Describe the bug**

After upgrading from `@react-pdf/renderer` version `3.2.1` to `3.3.1`, some of my PDFs are crashing with:

```
Error: dash(["4"], {}) invalid, lengths must be numeric and greater than zero
    at PDFDocument.dash (file:///home/proj/node_modules/.pnpm/@react-pdf+pdfkit@3.1.1/node_modules/@react-pdf/pdfkit/lib/pdfkit.js:1647:13)
    at setLineDash (file:///home/proj/node_modules/.pnpm/@react-pdf+render@3.3.2/node_modules/@react-pdf/render/lib/index.js:504:18)
    at drawNode (file:///home/proj/node_modules/.pnpm/@react-pdf+render@3.3.2/node_modules/@react-pdf/render/lib/index.js:601:3)
    at file:///home/proj/node_modules/.pnpm/@react-pdf+render@3.3.2/node_modules/@react-pdf/render/lib/index.js:629:5
    at Array.forEach (<anonymous>)
    at drawChildren (file:///home/proj/node_modules/.pnpm/@react-pdf+render@3.3.2/node_modules/@react-pdf/render/lib/index.js:626:12)
    at file:///home/proj/node_modules/.pnpm/@react-pdf+render@3.3.2/node_modules/@react-pdf/render/lib/index.js:630:5
    at Array.forEach (<anonymous>)
    at drawChildren (file:///home/proj/node_modules/.pnpm/@react-pdf+render@3.3.2/node_modules/@react-pdf/render/lib/index.js:626:12)
    at file:///home/proj/node_modules/.pnpm/@react-pdf+render@3.3.2/node_modules/@react-pdf/render/lib/index.js:630:5
    at Array.forEach (<anonymous>)
    at drawChildren (file:///home/proj/node_modules/.pnpm/@react-pdf+render@3.3.2/node_modules/@react-pdf/render/lib/index.js:626:12)
    at renderSvg (file:///home/proj/node_modules/.pnpm/@react-pdf+render@3.3.2/node_modules/@react-pdf/render/lib/index.js:707:3)
    at renderNode (file:///home/proj/node_modules/.pnpm/@react-pdf+render@3.3.2/node_modules/@react-pdf/render/lib/index.js:1876:17)
    at renderChild (file:///home/proj/node_modules/.pnpm/@react-pdf+render@3.3.2/node_modules/@react-pdf/render/lib/index.js:1859:12)
```

Rolling back to `3.2.1` makes the issue go away.

**To Reproduce**

I haven't yet been able to zero-in on exactly what code causes this crash. Wanted to get this issue up ASAP in case you have some ideas as to where the problem is coming from. The crash stacktrace isn't super helpful in tracking down where the issue is.

I'll keep trying to reproduce it and will report back here once I have a minimal repro.

**Expected behavior**

No crash

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Windows WSL (Linux Ubuntu)
 - Browser: N/A
 - React-pdf version: @react-pdf/renderer v3.3.1

**Comment by EvHaus** [comment]
I was able to create a repro. Seems it has to do with the `strokeDasharray` property on Svg elements. This code causes the failure:

```
import { Document, Page, PDFViewer, Line, Svg } from '@react-pdf/renderer';

const MyDocument = () => (
  <Document>
    <Page size="A4">
      <Svg height="300" viewBox="0 0 265 265" width="500">
        <Line
          stroke="red"
          strokeWidth="5"
          // Commenting out `strokeDasharray` makes the error go away
          strokeDasharray="5"
          x1="0"
          x2="265"
          y1="0"
          y2="265"
        />
      </Svg>
    </Page>
  </Document>
);

const App = () => (
  <div>
    <h1>React PDF Sample</h1>
    <PDFViewer height="600" width="800">
      <MyDocument />
    </PDFViewer>
  </div>
);

export default App;
```

And you can reproduce it here: https://stackblitz.com/edit/react-pdf-charts-starter-tt5ls1?file=src%2FApp.tsx

**Comment by wojtekmaj** [comment]
I'm no expert here but your code looks legit to me. Sounds like it should be handled. Just out of curiosity, does `strokeDasharray={5}` work?

**Comment by EvHaus** [comment]
No, I tried as well. Seems like any value given to `strokeDasharray` no longer works.

**Comment by EvHaus** [comment]
I was able to further track down the issue to `@react-pdf/pdfkit@3.1.1`. Rolling it back to 3.1.0 makes the issue go away.

**Comment by diegomura** [comment]
@EvHaus thanks for reporting. Will take a look. I recently added some changes to our pdfkit fork so we can (hope soon) remove it and use the base project. Unfortunately we still diverge a lot from it. Maybe one of those changes broke this case

**Comment by artemmatiushenko1** [comment]
It looks like it still crashes if we pass a string of two digits. For example "189 282". Version 3.4.4.

<img width="567" alt="image" src="https://github.com/diegomura/react-pdf/assets/71723893/185fdcf0-a6cb-493e-9c76-311f9e2c9a3d">
