### ISSUE TITLE
ISSUE IN REACT PDF

### ISSUE THREAD

**Issue by gaphel1** [diegomura/react-pdf#2647]
react-pdf.browser.es.js:4284 TypeError: o is not a function
    at textkit.js:1492:17
    at index.js:140:19
    at Array.map (<anonymous>)
    at textkit.js:2100:25
    at index.js:140:19
    at textkit.js:2102:12
    at YP (index.es.js:1881:15)
    at index.es.js:2692:37
    at Object.measure (index.esm.js:104:21)
    at index.esm.js:5500:27

**Comment by stefanwaltercode** [comment]
<img width="747" alt="error" src="https://github.com/diegomura/react-pdf/assets/114492092/7f3ee65b-377c-45b3-95fd-027dde875fbe">

**Comment by davidko5** [comment]
I have same issue. Also I have this only in production and not in dev mode for some reason

**Comment by diegomura** [comment]
I'll need a way to replicate this. Those error stacks do not provide any data
