### ISSUE TITLE
Cannot build the code on Next typescript v13 and React v18

### ISSUE THREAD

**Issue by mrzdtydlntm** [diegomura/react-pdf#2841]
I have an application build with Next TS v13 and React v18 using Node 18. I want to build my code and it said an error:

```
TypeError: (0 , $parcel$interopDefault(...)) is not a function
    at Object.<anonymous> (/home/mrzdtydlntm/Project/frontend/dashboard-ui/node_modules/.pnpm/fontkit@2.0.3/node_modules/fontkit/dist/main.cjs:5665:66)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/mrzdtydlntm/Project/frontend/dashboard-ui/node_modules/.pnpm/@react-pdf+pdfkit@3.0.4/node_modules/@react-pdf/pdfkit/lib/pdfkit.cjs.js:12:15)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)

> Build error occurred
Error: Failed to collect page data for /event/[eventCode]/candidate-management/report/[id]
    at /home/mrzdtydlntm/Project/frontend/dashboard-ui/node_modules/.pnpm/next@13.4.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1161:15 {
  type: 'Error'
}
```

I have change it by some suggested answer like using react-18-pdf/render, it import pdfJs etc, but it still can't build in my computer. it's only happen in ubuntu and docker, but in windows, it can builder. Can you help me on this issue? Thanks!!!

**Comment by apoco** [comment]
I hit this too, but `fontkit` seemed to be the issue. It looks like it's fixed if you bump that package. See https://github.com/foliojs/fontkit/issues/345.

**Comment by mrzdtydlntm** [comment]
@apoco thank you for the help! For now its fixed after i remove the fontkit
