### ISSUE TITLE
Cannot run examples

### ISSUE THREAD

**Issue by chadxz** [diegomura/react-pdf#286]
**OS:**
macOS High Sierra Version 10.13.6

**React-pdf version:**
v1.0.0-alpha.13-7-g154e6f5

**Description:**
When I try to follow the instructions in the README to run any of the examples I get an error.

**How to replicate issue including code snippet (if applies):**
```
react-pdf $ node -v
v8.11.3
react-pdf $ yarn install
yarn install v1.9.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
$ npm run build

> @react-pdf/renderer@1.0.0-alpha.14 build /Users/cmcelligott/src/react-pdf
> rimraf ./dist && rollup -c


./src/node.js → dist/react-pdf.es.js, dist/react-pdf.cjs.js...
Created bundle react-pdf.es.js: 92.82 kB → 21.64 kB (gzip)
Created bundle react-pdf.cjs.js: 93.96 kB → 21.82 kB (gzip)
created dist/react-pdf.es.js, dist/react-pdf.cjs.js in 1.2s

./src/node.js → dist/react-pdf.es.min.js, dist/react-pdf.cjs.min.js...
Created bundle react-pdf.es.min.js: 50.14 kB → 15.13 kB (gzip)
Created bundle react-pdf.cjs.min.js: 51.04 kB → 15.29 kB (gzip)
created dist/react-pdf.es.min.js, dist/react-pdf.cjs.min.js in 2s

./src/dom.js → dist/react-pdf.browser.es.js, dist/react-pdf.browser.cjs.js...
Created bundle react-pdf.browser.es.js: 128.38 kB → 26.35 kB (gzip)
Created bundle react-pdf.browser.cjs.js: 129.69 kB → 26.53 kB (gzip)
created dist/react-pdf.browser.es.js, dist/react-pdf.browser.cjs.js in 1.6s

./src/dom.js → dist/react-pdf.browser.es.min.js, dist/react-pdf.browser.cjs.min.js...
Created bundle react-pdf.browser.es.min.js: 63.83 kB → 16.97 kB (gzip)
Created bundle react-pdf.browser.cjs.min.js: 64.86 kB → 17.13 kB (gzip)
created dist/react-pdf.browser.es.min.js, dist/react-pdf.browser.cjs.min.js in 2.4s
✨  Done in 31.31s.
react-pdf $ yarn example -- fractals
yarn run v1.9.4
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ babel-node ./examples/index.js fractals
Running the fractals example
(node:67040) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pipe' of undefined
    at renderToFile (/Users/cmcelligott/src/react-pdf/dist/react-pdf.es.js:3596:10)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    at Function.Module.runMain (module.js:695:11)
    at Object.<anonymous> (/Users/cmcelligott/src/react-pdf/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
(node:67040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:67040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 2.52s.
react-pdf $
```

**Comment by chadxz** [comment]
I tried running the example on the README too using my own app setup, and get the same but a different line number because the distributed version uses sourcemaps:

```
TypeError: Cannot read property 'pipe' of undefined
    at renderToFile (/Users/cmcelligott/src/react-pdf-test/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:3603:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by ctxhou** [comment]
Same here

**Comment by prideaux** [comment]
@chadxz 

You might find this useful [https://github.com/diegomura/react-pdf/issues/62](https://github.com/diegomura/react-pdf/issues/62)
