### ISSUE TITLE
Error with PDFDownload Link

### ISSUE THREAD

**Issue by robSanders818** [diegomura/react-pdf#2911]
**Describe the bug**
I'm getting the following error while trying to use PDFDownloadLink to create a button to download the pdf: 
I should also say I am using material ui, and have a material ui table inside the document I am trying to render.  Looks like removing this component bypasses the error.
`react.development.js:1638 Uncaught TypeError: dispatcher.useInsertionEffect is not a function
    at useInsertionEffect (react.development.js:1638:1)
    at Insertion (emotion-styled-base.browser.esm.js:45:1)
    at Jd (react-reconciler.production.min.js:64:1)
    at ig (react-reconciler.production.min.js:160:1)
    at hg (react-reconciler.production.min.js:139:1)
    at bg (react-reconciler.production.min.js:138:1)
    at Of (react-reconciler.production.min.js:132:1)
    at react-reconciler.production.min.js:30:1
    at unstable_runWithPriority (scheduler.development.js:818:1)
    at hc (react-reconciler.production.min.js:29:1)Caused by: React ErrorBoundary TypeError: dispatcher.useInsertionEffect is not a function
    at PDFDownloadLink (http://127.0.0.1:3000/static/js/bundle.js:250444:5)`

**To Reproduce**
I'm using react 18.2/react-dom 18.2 and have the following component rendered in a file
`<PDFDownloadLink document={<Doc/>} fileName="fileName.pdf">
                            {({ blob, url, loading, error }) =>
                                loading ? 'Loading document...' : 'Download now!'
                              }</PDFDownloadLink>`

**Expected behavior**
A link showing to allow me to download the <Doc/> pdf

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- React-pdf version 4.0.0

**Comment by robSanders818** [comment]
> Does this happen in Next.js 15? Because I encountered similar issues with React Reconciler.

I'm not sure I'm not using Next.js personally but it wouldn't shock me

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by diegomura** [comment]
Can you provide a reprod case? I can't tell from the PR description what's going on
