### ISSUE TITLE
Add support for React 19

### ISSUE THREAD

**Issue by JacobWeisenburger** [diegomura/react-pdf#2935]
https://github.com/diegomura/react-pdf/blob/58f9a04740ed1331ef1dfa9999fb43c0ee10fa5b/packages/renderer/package.json#L39-L41

I tried updating to Next 15 and React 19, but @react-pdf/renderer didn't work properly, so I had to revert back to Next 14 and React 18

```
C:\Software\royal-dr…onents\Modal.tsx:24 TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at $$$reconciler (react-pdf.browser.js:134:11)
    at createRenderer (react-pdf.browser.js:4030:12)
    at pdf (react-pdf.browser.js:4237:28)
    at eval (react-pdf.browser.js:4485:31)
    at react-stack-bottom-frame (react-dom-client.development.js:22420:20)
    at runWithFiberInDEV (react-dom-client.development.js:544:16)
    at commitHookEffectListMount (react-dom-client.development.js:10732:29)
    at commitHookPassiveMountEffects (react-dom-client.development.js:10852:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12627:13)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12729:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12620:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12620:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12697:17)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12729:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12729:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12729:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12620:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12620:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12729:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12729:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12620:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12729:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12620:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12620:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12729:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12620:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12729:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12729:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12729:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12601:11)

The above error occurred in the <PDFViewer> component. It was handled by the <ReactDevOverlay> error boundary. Error Component Stack
    at PDFViewer (react-pdf.browser.js:4514:22)
    at dialog (<anonymous>)
    at Dialog (C:\Software\royal-dr…ts\Dialog.tsx:11:29)
    at Modal (C:\Software\royal-dr…nts\Modal.tsx:71:31)
    at Suspense (<anonymous>)
    at body (<anonymous>)
    at html (<anonymous>)
    at RootLayout (C:\Software\royal-dr…pp\layout.tsx:19:35)
    at ClientSegmentRoot (client-segment.js:14:11)
    at RedirectErrorBoundary (redirect-boundary.js:74:9)
    at RedirectBoundary (redirect-boundary.js:82:11)
    at NotFoundErrorBoundary (not-found-boundary.js:76:9)
    at NotFoundBoundary (not-found-boundary.js:84:11)
    at DevRootNotFoundBoundary (dev-root-not-found-boundary.js:33:11)
```

**Comment by diegomura** [comment]
Duplicated: https://github.com/diegomura/react-pdf/issues/2756

Please consider looking for existing issues before creating a new one. It was literally the first one on the issues page

**Comment by JacobWeisenburger** [comment]
> It was literally the first one on the issues page

![image](https://github.com/user-attachments/assets/aedf3f67-558f-4e9c-a925-d2af31bfa101)

it's on page 4 of the issues. So you are "literally" incorrect.

https://github.com/diegomura/react-pdf/issues?page=4&q=is%3Aissue+is%3Aopen

**Comment by diegomura** [comment]
With that filter yes, but GH automatically sort things by `updated-desc`. So it shows up first at least to me when I click "issues"

Page 1 or 4 is the least you can do to check. There's a search bar you can use too

<img width="874" alt="Screenshot 2024-11-14 at 5 13 43 PM" src="https://github.com/user-attachments/assets/0f233b11-e897-46c8-8d0a-3c7d12846d32">

**Comment by JacobWeisenburger** [comment]
I tried searching and nothing relavant came up:

![image](https://github.com/user-attachments/assets/98691a44-ad19-476f-92bb-e6018a8e02d7)
