### ISSUE TITLE
Using React 19 + Reconciler 0.31 breaks in production (Vercel)

### ISSUE THREAD

**Issue by Jussinevavuori** [diegomura/react-pdf#2966]
**Describe the bug**
`@react-pdf/renderer@4.1.4` with React 19 and React Reconciler 0.31 breaks in production environment with the following error message from the reconciler.

```
TypeError: Cannot read properties of undefined (reading 'S')
    at process.env.NODE_ENV.a.exports.l.exports (../../node_modules/@react-pdf/reconciler/lib/reconciler-31.js:10:88446)
    at k (../../node_modules/@react-pdf/reconciler/lib/reconciler-31.js:19:1068)
    at createRenderer (../../node_modules/@react-pdf/renderer/lib/react-pdf.js:85:10)
    at pdf (../../node_modules/@react-pdf/renderer/lib/react-pdf.js:210:26)
    at renderToStream (../../node_modules/@react-pdf/renderer/lib/react-pdf.js:368:20)
    at renderToBuffer (../../node_modules/@react-pdf/renderer/lib/react-pdf.js:395:35)
    at m (/var/task/apps/web/.next/server/chunks/7570.js:1:909)
    at async (/var/task/apps/web/.next/server/chunks/7570.js:1:27806)
    at async u.middlewares (/var/task/apps/web/.next/server/chunks/5151.js:2737:12109)
```

**To Reproduce**

1. Create new Next.js app

```sh
bun create next-app@latest
```

2. Create route handler at any endpoint.

```tsx
import { renderToBuffer, Document, Page, Text } from "@react-pdf/renderer";

const MinimalPdfDocument = () => (
  <Document>
    <Page style={{}}>
      <Text style={{}} fixed>
        Test
      </Text>
    </Page>
  </Document>
);

export async function GET() {
  const document = <MinimalPdfDocument />;
  const buffer = await renderToBuffer(document);
  return new Response(buffer, {
    headers: { "Content-Type": "application/pdf" },
  });
}
```

3. Deploy to Vercel
4. Access endpoint

**Expected behavior**
No error.

**Screenshots**
None.

**Desktop (please complete the following information):**

- OS: MacOS
- Server (vercel)
- React-pdf: Version `4.1.4` of `@react-pdf/renderer`

**Comment by Jussinevavuori** [comment]
Nevermind. These were caused by my own patches ([see more #2964](https://github.com/diegomura/react-pdf/issues/2964)) causing mismatching versions of React and the Reconciler.

If you see this error, ensure all React versions match. Do not override the `isReact19` check in `@react-pdf/reconciler/lib/index.js`.
