### ISSUE TITLE
npm run example

### ISSUE THREAD

**Issue by whizbz11** [diegomura/react-pdf#297]
when I run "npm run example",It's wrong
{ Error: Cannot find module './undefined/index'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at runExample (/Users/wanghao/code/git/react-pdf/examples/index.js:21:5)
    at Object.<anonymous> (/Users/wanghao/code/git/react-pdf/examples/index.js:38:3)

**Comment by diegomura** [comment]
That’s because you have to specify which example you want to run: 

```
npm run example — fractals
```

It’s on the README
