### ISSUE TITLE
Rendering in `route.tsx` Fails with Next.js 15

### ISSUE THREAD

**Issue by olikami** [diegomura/react-pdf#2976]
**Describe the bug**
Rendering a PDF Document in a `route.tsx` fails with Next.js v15.

**To Reproduce**
`app/route.tsx`:

```tsx
import { Document, Page, renderToBuffer, Text } from "@react-pdf/renderer";

export async function GET() {
  const pdf = await renderToBuffer(
    <Document>
      <Page>
        <Text>Hello world</Text>
      </Page>
    </Document>,
  );
  return new Response(pdf, {
    headers: {
      "Content-Type": "application/pdf",
    },
  });
}
```

**Expected behavior**

Open this in the browser and there should be an example PDF.

**Error**
```
 ✓ Compiled /test in 453ms (308 modules)
 ⨯ Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20props%2C%20_owner%2C%20_store%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Yn (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:15130)
    at <unknown> (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:19951)
    at Zt (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:29186)
    at pl (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:65072)
    at Hl (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:55055)
    at Vl (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:54983)
    at ql (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:54846)
    at jl (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:52005)
    at <unknown> (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:8017)
    at unstable_runWithPriority (/Users/oli/Developer/oli.cv/node_modules/.pnpm/scheduler@0.23.2/node_modules/scheduler/cjs/scheduler.development.js:317:12)
    at fn (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:7794)
    at mn (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:7962)
    at pn (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:7897)
    at Ul (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:49392)
    at r.updateContainer (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:67690)
    at updateContainer (node_modules/.pnpm/@react-pdf+renderer@4.1.4_react@18.3.1/node_modules/@react-pdf/renderer/src/index.js:32:13)
    at updateContainer (node_modules/.pnpm/@react-pdf+renderer@4.1.4_react@18.3.1/node_modules/@react-pdf/renderer/src/index.js:35:20)
    at pdf (node_modules/.pnpm/@react-pdf+renderer@4.1.4_react@18.3.1/node_modules/@react-pdf/renderer/src/node/renderTo.js:11:19)
    at renderToStream (node_modules/.pnpm/@react-pdf+renderer@4.1.4_react@18.3.1/node_modules/@react-pdf/renderer/src/node/renderTo.js:41:2)
    at renderToBuffer (app/test/route.tsx:4:34)
    at run (webpack://next/dist/src/server/route-modules/app-route/module.ts:529:41)
    at handler (webpack://next/dist/src/server/route-modules/app-route/module.ts:725:18)
    at fn (node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/src/server/lib/trace/tracer.ts:351:27)
    at NoopContextManager.with (/Users/oli/Developer/oli.cv/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/Users/oli/Developer/oli.cv/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/Users/oli/Developer/oli.cv/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/Users/oli/Developer/oli.cv/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at startActiveSpan (node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/src/server/lib/trace/tracer.ts:304:31)
    at NoopContextManager.with (/Users/oli/Developer/oli.cv/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/Users/oli/Developer/oli.cv/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at spanContext (node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/src/server/lib/trace/tracer.ts:303:24)
    at trace (webpack://next/dist/src/server/route-modules/app-route/module.ts:715:26)
    at run (webpack://next/dist/src/server/route-modules/app-route/module.ts:662:32)
    at run (webpack://next/dist/src/server/route-modules/app-route/module.ts:661:34)
    at run (webpack://next/dist/src/server/route-modules/app-route/module.ts:658:60)
    at handle (node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:2504:47)
    at doRender (node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:3027:27)
    at responseGenerator (node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/src/server/response-cache/index.ts:67:13)
    at get (node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:3039:48)
    at renderToResponseWithComponentsImpl (node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:1877:13)
    at fn (node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/src/server/lib/trace/tracer.ts:279:13)
    at trace (node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:1874:23)
    at renderToResponseWithComponents (node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:3597:26)
    at async DevServer.renderToResponseImpl (node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:3659:23)
    at async DevServer.pipeImpl (node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:1698:20)
    at async NextNodeServer.handleCatchallRenderRequest (node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.81.0/node_modules/next/src/server/next-server.ts:1034:6)
  30 |
  31 |   const updateContainer = (doc, callback) => {
> 32 |     renderer.updateContainer(doc, mountNode, null, callback);
     |             ^
  33 |   };
  34 |
  35 |   if (initialValue) updateContainer(initialValue);
 GET /test 500 in 734ms
 ⨯ Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20props%2C%20_owner%2C%20_store%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at GET (./app/test/route.tsx:14:90)
```

**Versions:**

```json
"dependencies": {
    "@react-pdf/renderer": "^4.0.0",
    "@types/node": "^22.5.1",
    "@types/react": "18.3.12",
    "@types/react-dom": "^18.3.0",
    "next": "15.0.3",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "typescript": "^5.5.4",
  },
```

**Comment by olikami** [comment]
The same also happens with react updated to v19 RC:

```
 ⨯ Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20props%2C%20_owner%2C%20_store%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Yn (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:15130)
    at <unknown> (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:19951)
    at Zt (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:29186)
    at pl (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:65072)
    at Hl (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:55055)
    at Vl (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:54983)
    at ql (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:54846)
    at jl (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:52005)
    at <unknown> (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:8017)
    at process.env.NODE_ENV.exports.unstable_runWithPriority (/Users/oli/Developer/oli.cv/node_modules/.pnpm/scheduler@0.25.0-rc.1/node_modules/scheduler/cjs/scheduler.development.js:288:16)
    at fn (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:7794)
    at mn (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:7962)
    at pn (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:7897)
    at Ul (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:49392)
    at r.updateContainer (node_modules/.pnpm/@react-pdf+reconciler@1.1.2/node_modules/@react-pdf/reconciler/lib/reconciler-26.js:1:67690)
    at updateContainer (node_modules/.pnpm/@react-pdf+renderer@4.1.4_react@19.0.0-rc.1/node_modules/@react-pdf/renderer/src/index.js:32:13)
    at updateContainer (node_modules/.pnpm/@react-pdf+renderer@4.1.4_react@19.0.0-rc.1/node_modules/@react-pdf/renderer/src/index.js:35:20)
    at pdf (node_modules/.pnpm/@react-pdf+renderer@4.1.4_react@19.0.0-rc.1/node_modules/@react-pdf/renderer/src/node/renderTo.js:11:19)
    at renderToStream (node_modules/.pnpm/@react-pdf+renderer@4.1.4_react@19.0.0-rc.1/node_modules/@react-pdf/renderer/src/node/renderTo.js:41:2)
    at renderToBuffer (app/test/route.tsx:4:34)
    at run (webpack://next/dist/src/server/route-modules/app-route/module.ts:529:41)
    at handler (webpack://next/dist/src/server/route-modules/app-route/module.ts:725:18)
    at fn (node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/src/server/lib/trace/tracer.ts:351:27)
    at NoopContextManager.with (/Users/oli/Developer/oli.cv/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/Users/oli/Developer/oli.cv/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/Users/oli/Developer/oli.cv/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/Users/oli/Developer/oli.cv/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at startActiveSpan (node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/src/server/lib/trace/tracer.ts:304:31)
    at NoopContextManager.with (/Users/oli/Developer/oli.cv/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/Users/oli/Developer/oli.cv/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at spanContext (node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/src/server/lib/trace/tracer.ts:303:24)
    at trace (webpack://next/dist/src/server/route-modules/app-route/module.ts:715:26)
    at run (webpack://next/dist/src/server/route-modules/app-route/module.ts:662:32)
    at run (webpack://next/dist/src/server/route-modules/app-route/module.ts:661:34)
    at run (webpack://next/dist/src/server/route-modules/app-route/module.ts:658:60)
    at handle (node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:2504:47)
    at doRender (node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:3027:27)
    at responseGenerator (node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/src/server/response-cache/index.ts:67:13)
    at get (node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:3039:48)
    at renderToResponseWithComponentsImpl (node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:1877:13)
    at fn (node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/src/server/lib/trace/tracer.ts:279:13)
    at trace (node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:1874:23)
    at renderToResponseWithComponents (node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:3597:26)
    at async DevServer.renderToResponseImpl (node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:3659:23)
    at async DevServer.pipeImpl (node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/src/server/base-server.ts:1698:20)
    at async NextNodeServer.handleCatchallRenderRequest (node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc.1_react@19.0.0-rc.1__react@19.0.0-rc.1_sass@1.81.0/node_modules/next/src/server/next-server.ts:1034:6)
  30 |
  31 |   const updateContainer = (doc, callback) => {
> 32 |     renderer.updateContainer(doc, mountNode, null, callback);
     |             ^
  33 |   };
  34 |
  35 |   if (initialValue) updateContainer(initialValue);
 GET /test 500 in 1098ms
 ⨯ Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20props%2C%20_owner%2C%20_store%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at GET (./app/test/route.tsx:14:90)

```

**Comment by olikami** [comment]
Deleting the `node_moduels` and `.next` did the trick.

**Comment by itaiperi** [comment]
I'm getting the exact same error as yours.
Node version 22.11.0, NextJS 15.1.0, @react-pdf/renderer is at 4.1.5, and lastly React is at 18.3.1.

Any ideas?

**Comment by alexincore** [comment]
Just had the same issue with 15.5.7... Solution:
Bump `react` and `react-dom` to 19+
I also had `@next/third-parties` that was outdated.
