### ISSUE TITLE
Error [ERR_REQUIRE_ESM] in @react-pdf/renderer with Next.js Despite Using ES Module Import

### ISSUE THREAD

**Issue by faezegholami** [diegomura/react-pdf#3017]
**Describe the bug**
I'm encountering an error while using @react-pdf/renderer in my Next.js project. The error occurs during the build process and indicates that I should use import() instead of require(). However, I am already importing the module using import, not require().

``` Error [ERR_REQUIRE_ESM]: require() of ES Module D:\....\node_modules\@react-pdf\renderer\lib\react-pdf.js from D:\....\.next\server\app\(routes)\(main)\landing\mvm\register\page.js not supported.
Instead change the require of react-pdf.js in D:\....\.next\server\app\(routes)\(main)\landing\mvm\register\page.js to a dynamic import() which is available in all CommonJS modules.
    at mod.require (D:\...\node_modules\next\dist\server\require-hook.js:65:28)
    at 29376 (D:\...\.next\server\app\(routes)\(main)\landing\mvm\register\page.js:1:314595)
    at Object.t [as require] (D:\....\.next\server\webpack-runtime.js:1:143)
    at require (D:\....\next\dist\compiled\next-server\app-page.runtime.prod.js:16:18365)
    at I (D:\.....\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:94362)
```

- OS: [e.g. MacOS, Windows]
- Browser [chrome]
- React-pdf version [^4.1.5]

**Comment by ToukoLohilahti** [comment]
Same. I tried to transpile it to es5 with babel but no luck. This is unfortunate because there is memory leak bug in 3.4.4 and parallel rendering bug with 3.4.5.

**Comment by ALI-KHALED-13** [comment]
Had the same issue
Using stable V22 of node fixes it too

**Comment by diegomura** [comment]
Same as https://github.com/diegomura/react-pdf/issues/3146 : react-pdf v4 is ESM-only. Next.js sometimes transpiles imports to require(). Make sure you've added @react-pdf/renderer to  serverComponentsExternalPackages in your next.config.js:

```
experimental: { serverComponentsExternalPackages: ['@react-pdf/renderer'] }         
```                                                              

Closing as a Next.js configuration issue.
