### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by moffsugita** [diegomura/react-pdf#397]
**OS:**
macOS 10.13.12

**React-pdf version:**

```
@react-pdf/renderer": "^1.0.0-alpha.25",
```

**Description:**

can't import...

**How to replicate issue including code snippet (if applies):**

```
(3,56): Could not find a declaration file for module '@react-pdf/renderer'. '/Users/me/proj/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js' implicitly has an 'any' type.
  Try `npm install @types/react-pdf__renderer` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-pdf__renderer';`
```
but I tried

```
npm install @types/react-pdf__renderer
npm ERR! code E404
npm ERR! 404 Not Found: @types/react-pdf__renderer@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2018-11-30T01_31_12_198Z-debug.log
```

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

```
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
```

**Comment by moffsugita** [comment]
```
> npm install -g flow-typed
/usr/local/bin/flow-typed -> /usr/local/lib/node_modules/flow-typed/dist/cli.js
+ flow-typed@2.5.1
added 175 packages in 12.201s
> flow-typed search react-pdf

• flow-typed cache not found, fetching from GitHub...done.

Found definitions:
╔═══════════╤═════════════════╤══════════════╗
║ Name      │ Package Version │ Flow Version ║
╟───────────┼─────────────────┼──────────────╢
║ react-pdf │ v2.1.x          │ >=v0.54.x    ║
╚═══════════╧═════════════════╧══════════════╝
```

## nice

https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-pdf_v2.1.x/flow_v0.54.x-/react-pdf_v2.1.x.js

```
vi package.json
moff@moffnoMacBook-puro ~/D/moff_day_care_react_dashboard> flow-typed install react-pdf
UNCAUGHT ERROR: Error: Failed to find a flow-bin dependency in package.json.
Please install flow-bin: `npm install --save-dev flow-bin`
    at findFlowSpecificVer$ (/usr/local/lib/node_modules/flow-typed/dist/lib/npm/npmProjectUtils.js:245:17)
    at tryCatch (/usr/local/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:117:21)
    at tryCatch (/usr/local/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:65:40)
    at invoke (/usr/local/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:155:20)
    at /usr/local/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:165:13
    at <anonymous>
```

tried
```
npm install --save-dev flow-bin
```

hmm.....
```
> flow-typed install react-pdf
Error: Unable to find a flow project in the current dir or any of it's parent dirs!
Please run this command from within a Flow project.
```

other issues...

https://github.com/wojtekmaj/react-pdf/issues/51

**Comment by moffsugita** [comment]
Ah. I should have ran `./node_modules/.bin/flow init` for making `.flowconfig` dir.

**Comment by moffsugita** [comment]
```
> ./node_modules/.bin/flow init
```

```
> flow-typed install react-pdf
Found ts-jest listed twice in package.json!
ERROR: Package not found from package.json.
```

hun? cuz' I installed like below.
`npm install --save-dev @react-pdf/renderer`

and

```
> npm install --save-dev react-pdf
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ts-jest@22.0.1 requires a peer of jest@^22.0.1 || ^22.1.0-alpha.1 || ^23.0.0-alpha.1 but none is installed. You must install peer dependencies yourself.

+ react-pdf@4.0.0
added 13 packages in 27.377s
```

however
```
> flow-typed install react-pdf
• Searching for 1 libdefs...
• rebasing flow-typed cache...
!! No flow@v0.87.0-compatible libdefs found in flow-typed for the explicitly requested libdefs. !!

Consider using `flow-typed create-stub react-pdf` to generate an empty libdef that you can fill in.
````

stub
```
> flow-typed create-stub react-pdf
• Creating 1 stub...
  • react-pdf@4.0.0
    └> flow-typed/npm/react-pdf_vx.x.x.js
```

I already "create-stub"!! why??
```
flow-typed install react-pdf
• Searching for 1 libdefs...
• rebasing flow-typed cache...
!! No flow@v0.87.0-compatible libdefs found in flow-typed for the explicitly requested libdefs. !!
```

version number??

```
mv flow-typed/npm/react-pdf_vx.x.x.js flow-typed/npm/react-pdf_v4.0.0.js
```

tried again

```
> flow-typed install react-pdf
• Searching for 1 libdefs...
!! No flow@v0.87.0-compatible libdefs found in flow-typed for the explicitly requested libdefs. !!

Consider using `flow-typed create-stub react-pdf` to generate an empty libdef that you can fill in.
```

I get nowhere!!!

**Comment by diegomura** [comment]
It was almost imposible to me to follow your line of thought through your comments. 
Just have in mind that `react-pdf` and `@react-pdf/renderer` are different libraries.
Also, never used `flow-typed` but I'm pretty sure there is no types definition for this library anywhere. Never worked with flow or typescript so there's nothing I can really do to help. Sorry about that.
The import failing is because something on your end not being able to load this lib from `node_modules`. Truly very hard to say based on what you said.

**Comment by moffsugita** [comment]
@diegomura 

> react-pdf and @react-pdf/renderer are different libraries
I'm sorry. I din't know that.
