### ISSUE TITLE
toBuffer doesn't handle error in render()

### ISSUE THREAD

**Issue by ronag** [diegomura/react-pdf#590]
`toBuffer` doesn't call `await` on render... thus any exception will be unhandled... such as "Font family not registered".

https://github.com/diegomura/react-pdf/blob/1bc45ae3da2740eb008df8b1486454cd0753fe65/src/index.js#L63

```js
{"level":30,"time":1556912171434,"msg":"unhandledRejection caught","pid":78,"hostname":"6f3e3bc080d6","name":"print-react","v":1}
{"level":60,"time":1556912171434,"msg":"error caused exit","pid":78,"hostname":"6f3e3bc080d6","name":"print-react","err":{"type":"Error","message":"Font family not registered: Open Sans. Please register it calling Font.register() method.","stack":"Error: Font family not registered: Open Sans. Please register it calling Font.register() method.\n    at getFont (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:2536:11)\n    at Object.load (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:2548:16)\n    at Document.loadFonts (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:3926:30)\n    at Document.loadAssets (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:3982:29)\n    at Document.render (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:4039:18)\n    at Root.render (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:60:25)\n    at Object.toBuffer (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:4318:15)\n    at renderToStream (/usr/src/app/node_modules/@react-pdf/renderer/dist/react-pdf.cjs.js:4352:23)\n    at Promise (/usr/src/app/src/print-react/publish.js:147:22)\n    at new Promise (<anonymous>)"},"v":1}

```

**Comment by diegomura** [comment]
Do you mind submitting a PR?
