### ISSUE TITLE
Getting Error : TypeError: Cannot set property 'getCurrentStack' of undefined

### ISSUE THREAD

**Issue by Fareedbaba** [diegomura/react-pdf#953]
**Describe the bug**
Am using the latest version i.e., 1.6.9

Getting exception in the function : 
function resetCurrentFiber() {
  {
    ReactDebugCurrentFrame.getCurrentStack = null;
    current = null;
    phase = null;
  }
}

and it entering into a endless loop
TypeError: Cannot set property 'getCurrentStack' of undefined\n    
at resetCurrentFiber (https://localhost:4321/dist/export-summary-web-part.js:104060:44)\n    
at handleError (https://localhost:4321/dist/export-summary-web-part.js:117598:7)\n    
at performSyncWorkOnRoot (https://localhost:4321/dist/export-summary-web-part.js:117338:11)\n    
at https://localhost:4321/dist/export-summary-web-part.js:105001:24\n    
at unstable_runWithPriority (https://localhost:4321/dist/export-summary-web-part.js:76255:12)\n    
at runWithPriority (https://localhost:4321/dist/export-summary-web-part.js:104951:10)\n    
at flushSyncCallbackQueueImpl (https://localhost:4321/dist/export-summary-web-part.js:104996:7)\n    
at flushSyncCallbackQueue (https://localhost:4321/dist/export-summary-web-part.js:104984:3)\n    
at scheduleUpdateOnFiber (https://localhost:4321/dist/export-summary-web-part.js:116774:9)\n

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows]
 - React-pdf version [e.g. v1.1.0]

**Comment by diegomura** [comment]
Duplicated #565
