### ISSUE TITLE
pdf.toBlob causes errors when run with TestCafe

### ISSUE THREAD

**Issue by xorxero** [diegomura/react-pdf#985]
**Describe the bug**

When calling pdf.toBlob, i get an error about no Blob constructor...
```

   1) A JavaScript error occurred on myappurl.
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      TypeError: Blob is not a constructor
          at BlobStream.push../node_modules/blob-stream/index.js.BlobStream.toBlob (http://localhost:3000/static/js/1.chunk.js:38727:18)
          at BlobStream.<anonymous> (http://localhost:3000/static/js/1.chunk.js:27626:39)
          at BlobStream.emit (http://localhost:3000/static/js/1.chunk.js:45224:35)
          at finishMaybe (http://localhost:3000/static/js/1.chunk.js:186893:14)
          at endWritable (http://localhost:3000/static/js/1.chunk.js:186902:3)
          at BlobStream.push../node_modules/stream-browserify/node_modules/readable-stream/lib/_stream_writable.js.Writable.end (http://localhost:3000/static/js/1.chunk.js:186851:41)
          at PDFDocument.onend (http://localhost:3000/static/js/1.chunk.js:185602:10)
          at Object.onceWrapper (http://localhost:3000/static/js/1.chunk.js:45300:54)
          at PDFDocument.emit (http://localhost:3000/static/js/1.chunk.js:45219:5)
          at endReadableNT (http://localhost:3000/static/js/1.chunk.js:186044:12)
          at afterTickTwo (http://localhost:3000/static/js/1.chunk.js:74106:12)
          at Item.push../node_modules/process/browser.js.Item.run (http://localhost:3000/static/js/1.chunk.js:74304:12)
          at drainQueue (http://localhost:3000/static/js/1.chunk.js:74268:43)
```

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):

``

Just call pdf.toBlob as button onclick, then test that button click using TestCafe.

_You can make use of [react-pdf REPL](https://react-pdf/repl) to share the snippet_

**Expected behavior**
No errors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MaCOS
 - Browser: Chrome
 - React-pdf version: 1.6.10

I kind of tried to write my own toBlob by using pdf.toString but had no luck, if someone has any idea, would appreciate that.

**Comment by diegomura** [comment]
Can you provide a way for me to replicate it? I didn't even know what TestCafe was, and can't setup and study any tool on my end, sorry. Simply do not have enough time. I'll be happy to check it with an appropriate way I can run and replicate this.
